import{NextResponse}from"next/server";import{z}from"zod";import{canVerifyDeposit}from"@/lib/permissions";import{guardFailed,guardFinancial,invalid,rpcFailure}from"@/lib/financial-route";import{notifyWithOptionalEmail}from"@/lib/notifications";
const schema=z.object({decision:z.enum(["approve","reject"]),reason:z.string().trim().max(500).optional()}).superRefine((value,ctx)=>{if(value.decision==="reject"&&!value.reason)ctx.addIssue({code:"custom",path:["reason"],message:"A rejection reason is required."})});
export async function POST(request:Request,{params}:{params:Promise<{id:string}>}){const context=await guardFinancial(canVerifyDeposit,"Payment verification access required.");if(guardFailed(context))return context;const parsed=schema.safeParse(await request.json().catch(()=>null));if(!parsed.success)return invalid(parsed.error.issues[0]?.message??"Invalid decision.");const{data,error}=await context.client.rpc("verify_customer_stay_payment",{p_payment_id:(await params).id,p_staff_user_id:context.actorId,p_approve:parsed.data.decision==="approve",p_reason:parsed.data.reason??null});if(error)return rpcFailure(error,{PAYMENT_NOT_FOUND:"That stay-payment submission no longer exists.",PAYMENT_NOT_PENDING:"This payment has already been reviewed.",PAYMENT_VERIFICATION_FORBIDDEN:"Payment verification access required."},"Unable to review this payment.");
 // Side channel: the guest learns the payment outcome without polling the portal.
 const result=data as{paymentId?:string;status?:string}|null;
 if(result?.paymentId&&result.status!=="pending_verification"){const approved=parsed.data.decision==="approve";const{data:payment}=await context.client.from("payments").select("id,invoice_id,reservation_id,amount").eq("id",result.paymentId).maybeSingle();
  if(payment?.invoice_id){const{data:invoice}=await context.client.from("invoices").select("id,reservation_id").eq("id",payment.invoice_id).maybeSingle();
   if(invoice?.reservation_id){const{data:reservation}=await context.client.from("reservations").select("id,user_id,confirmation_number,guest_email,room_type").eq("id",invoice.reservation_id).maybeSingle();
    if(reservation?.user_id)void notifyWithOptionalEmail({userId:reservation.user_id,type:approved?"stay_payment_verified":"stay_payment_rejected",title:approved?"Payment verified":"Payment could not be verified",detail:`PHP ${Number(payment.amount).toLocaleString("en-PH")} — ${reservation.confirmation_number}`,href:"/account/payments"},reservation.guest_email,{subject:approved?"Your payment has been verified":"Your payment could not be verified",heading:approved?"Your payment has been verified":"We could not verify your payment",bodyHtml:approved?`<p>Your stay payment of <strong>PHP ${Number(payment.amount).toLocaleString("en-PH")}</strong> for reservation <strong>${reservation.confirmation_number}</strong> has been applied to your folio.</p>`:`<p>We could not verify your stay payment for reservation <strong>${reservation.confirmation_number}</strong>.</p><p><em>Reason: ${parsed.data.reason}</em></p>`});}}}
 return NextResponse.json({data})}
