import{getServerSession}from"next-auth";import{NextResponse}from"next/server";import{authOptions}from"@/lib/auth";import{guestDetailsSchema,searchSchema}from"@/lib/booking";import{estimateTransfer,rideFare,TransferError,TRANSFER_CODES}from"@/lib/transfer";import type{TransferEstimate}from"@/lib/transfer";import{supabase}from"@/lib/supabase";
export async function POST(request:Request){const session=await getServerSession(authOptions);if(!session||session.user.disabled)return NextResponse.json({error:"Sign in to continue your reservation."},{status:401});if(session.user.role!=="guest")return NextResponse.json({error:"Customer access required."},{status:403});if(!supabase)return NextResponse.json({error:"Booking is temporarily unavailable."},{status:503});try{const parsed=guestDetailsSchema.safeParse(await request.json());if(!parsed.success)return NextResponse.json({error:parsed.error.issues[0]?.message??"Check your guest details."},{status:400});const search=searchSchema.safeParse({checkIn:parsed.data.checkIn,checkOut:parsed.data.checkOut,guests:parsed.data.guests});if(!search.success)return NextResponse.json({error:search.error.issues[0]?.message??"Invalid stay dates."},{status:400});const p=parsed.data;
  // Transport is real money once verified and client prices are never trusted: re-derive any
  // chosen ride server-side (TomTom geocode + route + the live vehicle rates) and freeze the
  // fare the server computes into the stored transport_lines element. One optional ride.
  const rides=p.transportLines??[];
  let transportLines:unknown[]=rides;
  if(rides.length){
   const ride=rides[0];
   const{data:vehicles,error:vehicleError}=await supabase.from("transport_vehicle_types").select("id,name,base_fare,per_km,per_minute,booking_fee").eq("active",true);
   if(vehicleError)throw vehicleError;
   const vehicle=(vehicles??[]).find((row)=>String(row.id)===ride.vehicleTypeId);
   if(!vehicle)return NextResponse.json({error:"That transfer vehicle is no longer offered. Please review your selection and try again."},{status:409});
   let estimate:TransferEstimate;try{estimate=await estimateTransfer(ride.pickupAddress)}catch(error){if(error instanceof TransferError&&error.code===TRANSFER_CODES.GEOCODE)return NextResponse.json({error:error.message},{status:422});if(error instanceof TransferError)return NextResponse.json({error:"We could not confirm your transfer fare. Please try again or remove the transfer."},{status:503});throw error;}
   const fare=rideFare({baseFare:Number(vehicle.base_fare),perKm:Number(vehicle.per_km),perMinute:Number(vehicle.per_minute),bookingFee:Number(vehicle.booking_fee)},estimate.distanceKm,estimate.durationMin);
   if(!(fare.total>0))return NextResponse.json({error:"That vehicle is not bookable at this fare."},{status:409});
   transportLines=[{name:`Hotel transfer · ${vehicle.name} · ${estimate.distanceKm.toFixed(1)} km`,price:fare.total,note:ride.note,ride:{vehicleTypeId:vehicle.id,vehicleName:vehicle.name,pickupAddress:estimate.pickupAddress,dropoffLabel:estimate.dropoffLabel,distanceKm:Number(estimate.distanceKm.toFixed(2)),durationMin:Number(estimate.durationMin.toFixed(1)),fare}}];
  }
  const{data,error}=await supabase.rpc("create_booking_hold",{p_user_id:session.user.id,p_room_type:p.roomType,p_check_in:p.checkIn,p_check_out:p.checkOut,p_guest_count:p.guests,p_first_name:p.firstName,p_last_name:p.lastName,p_email:p.email,p_mobile:p.mobile,p_address:p.address||null,p_nationality:p.nationality||null,p_expected_arrival:p.expectedArrival||null,p_request_options:p.requestOptions,p_transport_lines:transportLines,p_special_requests:p.specialRequests||null});if(error){if(error.message.includes("ROOM_TYPE_UNAVAILABLE"))return NextResponse.json({error:"Availability changed while you were booking. Please choose another available room."},{status:409});throw error;}return NextResponse.json({token:data},{status:201});}catch{return NextResponse.json({error:"We could not hold this room. Please try again."},{status:500})}}
