import{getServerSession}from"next-auth";import{NextResponse}from"next/server";import{authOptions}from"@/lib/auth";import{guestDetailsSchema,searchSchema}from"@/lib/booking";import{supabase}from"@/lib/supabase";import{sendEmail,guestEmailHtml}from"@/lib/email";
export async function POST(request:Request){const session=await getServerSession(authOptions);if(!session||session.user.disabled)return NextResponse.json({error:"Sign in to continue your reservation."},{status:401});if(session.user.role!=="guest")return NextResponse.json({error:"Customer access required."},{status:403});if(!supabase)return NextResponse.json({error:"Booking is temporarily unavailable."},{status:503});try{const parsed=guestDetailsSchema.safeParse(await request.json());if(!parsed.success)return NextResponse.json({error:parsed.error.issues[0]?.message??"Check your guest details."},{status:400});const search=searchSchema.safeParse({checkIn:parsed.data.checkIn,checkOut:parsed.data.checkOut,guests:parsed.data.guests});if(!search.success)return NextResponse.json({error:search.error.issues[0]?.message??"Invalid stay dates."},{status:400});const p=parsed.data;
  // Transport is no longer sold at checkout (replaced by the standalone Transportation
  // Service). The RPC still accepts transport_lines; existing reservations keep theirs.
  // An optional transportation ride REQUEST (preferences) may ride along, though — filed
  // as a REQUESTED row once the reservation is confirmed.
  const{data,error}=await supabase.rpc("create_booking_hold",{p_user_id:session.user.id,p_room_type:p.roomType,p_check_in:p.checkIn,p_check_out:p.checkOut,p_guest_count:p.guests,p_first_name:p.firstName,p_last_name:p.lastName,p_email:p.email,p_mobile:p.mobile,p_address:p.address||null,p_nationality:p.nationality||null,p_expected_arrival:p.expectedArrival||null,p_request_options:p.requestOptions,p_transport_lines:[],p_transportation_preferences:p.transportationPreferences??null,p_special_requests:p.specialRequests||null});if(error){if(error.message.includes("ROOM_TYPE_UNAVAILABLE"))return NextResponse.json({error:"Availability changed while you were booking. Please choose another available room."},{status:409});if(error.message.includes("INVALID_TRANSPORTATION_PREFERENCES"))return NextResponse.json({error:"Check your transportation request details and try again."},{status:400});throw error;}
 // Payment-link email (the hold token IS the payment link credential). Pure
 // side channel — an email failure never fails the hold.
 if(p.email){const base=process.env.NEXTAUTH_URL??"http://localhost:3000";void sendEmail({to:p.email,subject:"Your Haven booking is held for 15 minutes",html:guestEmailHtml("Your room is held — 15 minutes to pay",`<p>We are holding your ${p.roomType} from ${p.checkIn} to ${p.checkOut} for 15 minutes.</p><p>Submit your deposit to secure the booking:</p><p style="margin:24px 0"><a href="${base}/booking/payment/${data}" style="display:inline-block;background:#8a7a55;color:#ffffff;padding:12px 24px;border-radius:8px;text-decoration:none">Submit your deposit</a></p><p>If the link no longer works, the hold has expired — simply search your dates again.</p>`)});}
return NextResponse.json({token:data},{status:201});}catch{return NextResponse.json({error:"We could not hold this room. Please try again."},{status:500})}}
