import{NextResponse}from"next/server";import{z}from"zod";import{canCancelTransportation,canOperateTransportation,canViewTransportation}from"@/lib/permissions";import{guardTransportation,transportationGuardFailed,transportationRpcFailure}from"@/lib/transportation-route";import{notifyWithOptionalEmail}from"@/lib/notifications";
const schema=z.object({action:z.enum(["REVIEW","SCHEDULE","ASSIGN","START","COMPLETE","CANCEL","REJECT"]),expectedVersion:z.number().int().min(1),details:z.object({driverName:z.string().trim().max(120).optional(),vehicleTypeId:z.string().uuid().optional(),pickupDate:z.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional(),pickupTime:z.string().regex(/^([01]\d|2[0-3]):[0-5]\d$/).optional(),staffNotes:z.string().trim().max(500).optional(),customerVisibleNotes:z.string().trim().max(500).optional(),reason:z.string().trim().min(1,"A reason is required.").max(300).optional()}).default({})});
const OPERATIONAL=["REVIEW","SCHEDULE","ASSIGN","START","COMPLETE"]as const;
export async function POST(request:Request,{params}:{params:Promise<{id:string}>}){const context=await guardTransportation(canViewTransportation);if(transportationGuardFailed(context))return context;try{const parsed=schema.safeParse(await request.json());if(!parsed.success)return NextResponse.json({error:parsed.error.issues[0]?.message??"Invalid transportation action."},{status:400});const{action,expectedVersion,details}=parsed.data;
// Front Desk executes the operational path; CANCEL/REJECT are also open to the Manager.
if((OPERATIONAL as readonly string[]).includes(action)&&!canOperateTransportation(context.role))return NextResponse.json({error:"Only the Front Desk operates transportation services."},{status:403});
if(!canOperateTransportation(context.role)&&!canCancelTransportation(context.role))return NextResponse.json({error:"Transportation action access required."},{status:403});
if((action==="CANCEL"||action==="REJECT")&&!details.reason)return NextResponse.json({error:"A reason is required."},{status:400});
const{data,error}=await context.client.rpc("staff_transition_transportation_request",{p_request_id:(await params).id,p_action:action,p_details:details,p_staff_user_id:context.actorId,p_expected_version:expectedVersion});if(error)return transportationRpcFailure(error,{TRANSPORTATION_REQUEST_NOT_FOUND:"Transportation request not found.",TRANSPORTATION_TRANSITION_INVALID:"That status change is not allowed from the request's current status.",TRANSPORTATION_REQUEST_STALE:"This request was just updated by someone else. Refresh and try again.",TRANSPORTATION_AUTHORITY_REQUIRED:"Your role cannot perform this transportation action.",TRANSPORTATION_REASON_REQUIRED:"A reason is required.",INVALID_DRIVER_ASSIGNMENT:"Enter the driver's name.",INVALID_VEHICLE_TYPE:"Choose a valid vehicle type.",INVALID_TRANSPORTATION_SCHEDULE:"Choose a valid date and time.",TRANSPORTATION_RESERVATION_NOT_READY:"The reservation is no longer active, so the fare cannot be posted.",FOLIO_NOT_FOUND:"No folio exists for this reservation yet."},"Unable to update this transportation request.");
// Side channel: SCHEDULE is the first guest-visible fact (their pickup time),
// CANCEL/REJECT needs a reason they can read. Other transitions stay silent —
// driver assignment and dispatch are internal operations.
try{if(action==="SCHEDULE"||action==="CANCEL"||action==="REJECT"){const{data:trip}=await context.client.from("transportation_requests").select("id,reservation_id,service_type,pickup_location,dropoff_location,pickup_date,pickup_time").eq("id",(await params).id).maybeSingle();
 if(trip?.reservation_id){const{data:reservation}=await context.client.from("reservations").select("id,user_id,confirmation_number,guest_email,room_type").eq("id",trip.reservation_id).maybeSingle();
  if(reservation?.user_id){const cancelled=action!=="SCHEDULE";
   void notifyWithOptionalEmail({userId:reservation.user_id,type:cancelled?"transportation_cancelled":"transportation_scheduled",title:cancelled?"Transportation request cancelled":"Transportation scheduled",detail:cancelled?(details.reason??`Your transportation request was cancelled.`):`Pickup ${trip.pickup_date} ${trip.pickup_time} — ${trip.pickup_location} → ${trip.dropoff_location}`,href:"/account/transportation"},reservation.guest_email,{subject:cancelled?"Your Haven transportation was cancelled":"Your Haven transportation is scheduled",heading:cancelled?"Your transportation was cancelled":"Your transportation is scheduled",bodyHtml:cancelled?`<p>Your transportation request for reservation <strong>${reservation.confirmation_number}</strong> was cancelled.</p><p><em>Reason: ${details.reason}</em></p>`:`<p>Your ride for reservation <strong>${reservation.confirmation_number}</strong> is scheduled.</p><table style="font-size:14px;line-height:1.8"><tr><td style="color:#8a8a8a">Pickup</td><td>${trip.pickup_date} at ${trip.pickup_time}</td></tr><tr><td style="color:#8a8a8a">Route</td><td>${trip.pickup_location} → ${trip.dropoff_location}</td></tr></table>`});}}}
}catch{/* notification lookup failure never blocks the transition response */}
return NextResponse.json({data})}catch{return NextResponse.json({error:"Unable to update this transportation request."},{status:500})}}
