import{getServerSession}from"next-auth";import{NextResponse}from"next/server";import{z}from"zod";import{authOptions}from"@/lib/auth";import{supabase}from"@/lib/supabase";import{notifyWithOptionalEmail}from"@/lib/notifications";
const schema=z.object({batchId:z.string().uuid(),decision:z.enum(["approve","reject"]),note:z.string().trim().max(500).optional()});
// Front Desk approves or declines a customer's guest-request submission (one
// decision covers every item in the batch). Other roles have no button to reach this.
export async function POST(request:Request){const session=await getServerSession(authOptions);if(!session||session.user.disabled)return NextResponse.json({error:"Unauthorized"},{status:401});if(session.user.role!=="front_desk")return NextResponse.json({error:"Front Desk request access required."},{status:403});if(!supabase)return NextResponse.json({error:"Database unavailable."},{status:503});const parsed=schema.safeParse(await request.json());if(!parsed.success)return NextResponse.json({error:"A batch and decision are required."},{status:400});if(parsed.data.decision==="reject"&&!parsed.data.note)return NextResponse.json({error:"A reason is required to decline a request."},{status:400});try{const{data,error}=await supabase.rpc("front_desk_review_guest_request_batch",{p_staff_user_id:session.user.id,p_batch_id:parsed.data.batchId,p_decision:parsed.data.decision,p_note:parsed.data.note??null});if(error){if(error.message.includes("ALREADY_REVIEWED"))return NextResponse.json({error:"This submission was already reviewed."},{status:409});if(error.message.includes("FRONT_DESK_ACCESS_REQUIRED"))return NextResponse.json({error:"Front Desk request access required."},{status:403});throw error}
 // Side channel: the guest learns the batch outcome. One notification for the
 // whole batch — the decision covered every item in it.
 try{const approved=parsed.data.decision==="approve";const{data:requests}=await supabase.from("guest_requests").select("batch_id,approval_status,reservation_id").eq("batch_id",parsed.data.batchId).limit(1);const owner=(requests??[])[0];
  if(owner?.reservation_id){const{data:reservation}=await supabase.from("reservations").select("id,user_id,confirmation_number,guest_email,room_type").eq("id",owner.reservation_id).maybeSingle();
   if(reservation?.user_id)void notifyWithOptionalEmail({userId:reservation.user_id,type:"request_batch_reviewed",title:approved?"Your requests were approved":"Your requests were declined",detail:approved?`Your request submission for ${reservation.room_type} was approved.`:`${parsed.data.note??"Your request submission was declined."}`,href:"/account/requests"},reservation.guest_email,{subject:approved?"Your Haven requests were approved":"Your Haven requests were declined",heading:approved?"Your requests were approved":"Your requests were declined",bodyHtml:`<p>Your request submission for reservation <strong>${reservation.confirmation_number}</strong> was ${approved?"approved and passed to our teams":"declined"}.</p>${approved?"":`<p><em>Reason: ${parsed.data.note}</em></p>`}`});}
 }catch{/* notification lookup failure never blocks the review response */}
 return NextResponse.json({data:{reviewedCount:data}})}catch{return NextResponse.json({error:"Unable to review this submission."},{status:500})}}
