import Link from "next/link";
import { getServerSession } from "next-auth";
import { notFound, redirect } from "next/navigation";
import { CheckCircle2, Clock3 } from "lucide-react";
import { authOptions } from "@/lib/auth";
import { BookingPageFrame } from "@/components/booking/booking-page-frame";
import { calculateFinancialState, calculateNights, formatPeso, policyFromSnapshot, transportTotal } from "@/lib/booking";
import { friendlyStatus, getCustomerReservationDetail } from "@/lib/customer";
export default async function ConfirmationPage({params}:{params:Promise<{id:string}>}){const session=await getServerSession(authOptions);const{id}=await params;if(!session)redirect(`/login?callbackUrl=${encodeURIComponent(`/booking/confirmation/${id}`)}`);if(session.user.role!=="guest")redirect("/manager_dashboard");const reservation=await getCustomerReservationDetail(session.user.id,id);if(!reservation)notFound();const finance=calculateFinancialState(reservation.invoice?.amount??reservation.total,reservation.invoice?.paid??reservation.deposit??0);const confirmed=reservation.status==="confirmed";const policy=policyFromSnapshot(reservation.deposit_policy_snapshot);const transport=Array.isArray(reservation.transport_lines)?(reservation.transport_lines as {name:string;price:number|string;note?:string|null}[]).filter((line)=>line&&Number(line.price)>0):[];return <BookingPageFrame session={session} step={confirmed?"Confirmed":"Verification pending"}><section className="confirmation-card deposit-confirmation">{confirmed?<CheckCircle2/>:<Clock3/>}<p className="eyebrow">{confirmed?"Reservation confirmed":"Deposit awaiting verification"}</p><h1>{confirmed?"Your Haven stay is reserved.":"Your payment reference was submitted."}</h1><p>{confirmed?"Haven verified your reservation deposit.":"Your reservation is not confirmed yet. Front Desk or Accounting must verify the submitted deposit before the hold expires."}</p><p className="confirmation-number">{reservation.confirmation_number}</p><dl><div><dt>Room type</dt><dd>{reservation.room_type}</dd></div><div><dt>Dates</dt><dd>{reservation.check_in} - {reservation.check_out}</dd></div><div><dt>Nights / guests</dt><dd>{calculateNights(reservation.check_in,reservation.check_out)} / {reservation.guests}</dd></div><div><dt>Stay total</dt><dd>{formatPeso(finance.total)}</dd></div>{transport.length>0&&<div className="dl-note-row"><dt>Hotel transport</dt><dd>{transport.map((line)=>line.name).join(", ")}<small className="summary-note">{formatPeso(transportTotal(transport))} — included in the stay total above and covered by the reservation deposit.</small></dd></div>}<div><dt>Required reservation deposit</dt><dd>{formatPeso(reservation.deposit_required??0)}</dd></div><div><dt>Deposit paid</dt><dd>{formatPeso(finance.paid)}</dd></div><div><dt>Remaining balance</dt><dd>{formatPeso(finance.balance)}</dd></div><div><dt>Reservation</dt><dd>{friendlyStatus(reservation.status)}</dd></div><div><dt>Payment</dt><dd>{friendlyStatus(reservation.invoice?.status??reservation.payment_status)}</dd></div></dl><p className="remaining-policy">Remaining balance due: {policy.remainingBalanceDue}.</p><div><Link className="btn btn-accent" href={`/my-reservations/${reservation.id}`}>Manage reservation</Link><Link className="btn btn-soft" href="/account">Customer portal</Link></div></section></BookingPageFrame>}
