import { describe, expect, it } from "vitest";
import { calculateNights, countAvailableUnits, isBlockingReservationStatus, rangesOverlap, safeInternalPath, searchSchema, transportLinesSchema, transportRideSchema, transportTotal } from "@/lib/booking";
const date=(offset:number)=>{const value=new Date();value.setUTCDate(value.getUTCDate()+offset);return value.toISOString().slice(0,10)};
describe("guest booking rules",()=>{
  it("calculates nights without timezone drift",()=>expect(calculateNights("2026-09-04","2026-09-07")).toBe(3));
  it("allows same-day turnover",()=>expect(rangesOverlap("2026-09-01","2026-09-04","2026-09-04","2026-09-07")).toBe(false));
  it("detects a real date overlap",()=>expect(rangesOverlap("2026-09-01","2026-09-05","2026-09-04","2026-09-07")).toBe(true));
  it("blocks active reservations but not cancelled stays",()=>{expect(isBlockingReservationStatus("confirmed")).toBe(true);expect(isBlockingReservationStatus("checked_in")).toBe(true);expect(isBlockingReservationStatus("cancelled")).toBe(false)});
  it("rejects past and reversed dates",()=>{expect(searchSchema.safeParse({checkIn:date(-1),checkOut:date(1),guests:2}).success).toBe(false);expect(searchSchema.safeParse({checkIn:date(2),checkOut:date(1),guests:2}).success).toBe(false)});
  it("accepts a valid search",()=>expect(searchSchema.safeParse({checkIn:date(1),checkOut:date(3),guests:2}).success).toBe(true));
  it("excludes administratively inactive and Maintenance-blocked inventory",()=>{const window={checkIn:"2026-09-05",checkOut:"2026-09-07",now:"2026-09-01T00:00:00Z",today:"2026-09-01"};const rows={rooms:[{id:"safe",type:"King",status:"available",housekeeping:"clean",administratively_active:true},{id:"inactive",type:"King",status:"available",housekeeping:"clean",administratively_active:false},{id:"blocked",type:"King",status:"available",housekeeping:"clean",administratively_active:true}],reservations:[],holds:[],blockedRoomIds:new Set(["blocked"])};expect(countAvailableUnits("King",window,rows)).toBe(1)});
  it("rejects open redirects while preserving internal booking URLs",()=>{expect(safeInternalPath("https://evil.example/steal","/")).toBe("/");expect(safeInternalPath("//evil.example/steal","/")).toBe("/");expect(safeInternalPath("/booking/details?roomType=Deluxe+King","/")).toBe("/booking/details?roomType=Deluxe+King")});
});
describe("hotel transfer ride",()=>{
  it("parses one pickup ride and defaults the note",()=>{expect(transportRideSchema.parse({pickupAddress:"  NAIA Terminal 3, Pasay  ",vehicleTypeId:" abc "})).toMatchObject({pickupAddress:"NAIA Terminal 3, Pasay",vehicleTypeId:"abc",note:""});expect(transportRideSchema.safeParse({pickupAddress:"NAIA",vehicleTypeId:"abc"}).success).toBe(false);expect(transportRideSchema.safeParse({pickupAddress:"NAIA Terminal 3, Pasay",vehicleTypeId:""}).success).toBe(false)});
  it("caps a booking at one optional ride",()=>{const ride={pickupAddress:"NAIA Terminal 3, Pasay",vehicleTypeId:"abc"};expect(transportLinesSchema.safeParse([ride,ride]).success).toBe(false);expect(transportLinesSchema.safeParse([ride]).success).toBe(true);expect(transportLinesSchema.parse(undefined)).toEqual([])});
  it("sums stored transport lines centavo-safe without rounding drift",()=>{expect(transportTotal(null)).toBe(0);expect(transportTotal([{name:"a",price:0.1},{name:"b",price:0.2}])).toBeCloseTo(0.3,10);expect(transportTotal([{name:"a",price:1850},{name:"b",price:900.5}])).toBe(2750.5)});
});