import { supabase } from "@/lib/supabase";
import { calculateNights, hotelToday } from "@/lib/booking";

export type ReservationCategory = "current" | "upcoming" | "past" | "cancelled";
const STATUS_LABELS: Record<string,string> = {
  checked_in:"Checked in",checked_out:"Checked out",in_progress:"In progress",no_show:"No-show",
  manual_bank_transfer:"Bank transfer",manual_gcash:"GCash",manual_refund:"Refund",
  partial:"Partially paid",deposit:"Deposit paid",reservation_deposit:"Reservation deposit",stay_payment:"Stay payment",refund:"Refund",
  pending_verification:"Awaiting verification",refund_pending:"Refund pending",partial_refund:"Partially refunded",refunded:"Refunded",
  unpaid:"Unpaid",paid:"Paid",failed:"Failed",expired:"Expired"
};
export const friendlyStatus=(value:string)=>STATUS_LABELS[value]??value.replaceAll("_"," ").replace(/^./,(char)=>char.toUpperCase());
export const formatStayDate=(value:string)=>new Intl.DateTimeFormat("en-PH",{month:"short",day:"numeric",year:"numeric",timeZone:"UTC"}).format(new Date(`${value}T00:00:00Z`));
export function formatStayRange(checkIn:string,checkOut:string){const start=new Date(`${checkIn}T00:00:00Z`),end=new Date(`${checkOut}T00:00:00Z`);const sameYear=start.getUTCFullYear()===end.getUTCFullYear();const first=new Intl.DateTimeFormat("en-PH",{month:"short",day:"numeric",...(sameYear?{}:{year:"numeric"}),timeZone:"UTC"}).format(start);const last=new Intl.DateTimeFormat("en-PH",{month:"short",day:"numeric",year:"numeric",timeZone:"UTC"}).format(end);return `${first} - ${last}`}
export function reservationCategory(reservation:{status:string;check_in:string;check_out:string},today=hotelToday()):ReservationCategory{if(["cancelled","no_show"].includes(reservation.status))return"cancelled";if(reservation.status==="checked_in")return"current";if(reservation.status==="checked_out"||reservation.check_out<=today)return"past";return"upcoming"}
export function groupReservations<T extends{status:string;check_in:string;check_out:string}>(reservations:T[],today=hotelToday()){const groups:Record<ReservationCategory,T[]>={current:[],upcoming:[],past:[],cancelled:[]};for(const reservation of reservations)groups[reservationCategory(reservation,today)].push(reservation);groups.current.sort((a,b)=>a.check_out.localeCompare(b.check_out));groups.upcoming.sort((a,b)=>a.check_in.localeCompare(b.check_in));groups.past.sort((a,b)=>b.check_out.localeCompare(a.check_out));groups.cancelled.sort((a,b)=>b.check_in.localeCompare(a.check_in));return groups}

const financialColumns="id,confirmation_number,room_type,check_in,check_out,guests,status,total,deposit,deposit_required,deposit_policy_snapshot,operational_policy_snapshot,payment_due_at,payment_status,cancellation_reason,identity_status";
export async function getCustomerFinancials(userId:string){
  if(!supabase)return[];await supabase.rpc("expire_booking_holds");
  const{data:reservations,error:reservationError}=await supabase.from("reservations").select(financialColumns).eq("user_id",userId).order("check_in",{ascending:false});if(reservationError)throw reservationError;
  const ids=(reservations??[]).map((item)=>item.id);if(!ids.length)return[];
  const{data:invoices,error:invoiceError}=await supabase.from("invoices").select("id,reservation_id,amount,paid,balance,status,method,due_date,created_at").in("reservation_id",ids);if(invoiceError)throw invoiceError;
  const invoiceIds=(invoices??[]).map((item)=>item.id);
  const [paymentResult,chargeResult,refundResult,changeResult,adjustmentResult,documentResult]=await Promise.all([
    invoiceIds.length?supabase.from("payments").select("id,invoice_id,reservation_id,amount,currency,method,reference,purpose,status,submitted_at,verified_at,created_at").in("invoice_id",invoiceIds).order("created_at",{ascending:false}):Promise.resolve({data:[]}),
    invoiceIds.length?supabase.from("folio_charges").select("id,invoice_id,reservation_id,description,category,amount,status,created_at").in("invoice_id",invoiceIds).order("created_at",{ascending:false}):Promise.resolve({data:[]}),
    supabase.from("refund_requests").select("id,reservation_id,reason,paid_deposit,refund_basis_points,eligible_amount,status,reference,processed_at,created_at").in("reservation_id",ids).order("created_at",{ascending:false}),
    supabase.from("reservation_change_requests").select("id,reservation_id,requested_check_in,requested_check_out,requested_room_type,requested_guests,requested_special_requests,calculated_total,payment_difference,execution_status,reason,status,created_at").in("reservation_id",ids).order("created_at",{ascending:false}),
    supabase.from("financial_adjustments").select("id,invoice_id,reservation_id,transaction_type,direction,amount,reason,created_at").in("reservation_id",ids).order("created_at",{ascending:false}),
    supabase.from("financial_documents").select("id,document_number,document_type,reservation_id,payment_id,created_at").in("reservation_id",ids).order("created_at",{ascending:false})
  ]);
  return(reservations??[]).map((reservation)=>{const invoice=(invoices??[]).find((item)=>item.reservation_id===reservation.id);return{...reservation,invoice:invoice??null,payments:invoice?(paymentResult.data??[]).filter((payment)=>payment.invoice_id===invoice.id):[],charges:invoice?(chargeResult.data??[]).filter((charge)=>charge.invoice_id===invoice.id):[],refunds:(refundResult.data??[]).filter((refund)=>refund.reservation_id===reservation.id),changeRequests:(changeResult.data??[]).filter((request)=>request.reservation_id===reservation.id),adjustments:(adjustmentResult.data??[]).filter((adjustment)=>adjustment.reservation_id===reservation.id),documents:(documentResult.data??[]).filter((document)=>document.reservation_id===reservation.id)}});
}
export async function getCustomerRequests(userId:string){if(!supabase)return[];const{data:reservations,error}=await supabase.from("reservations").select("id,confirmation_number,room_type,status,guest_id").eq("user_id",userId);if(error)throw error;const ids=(reservations??[]).map((item)=>item.id);if(!ids.length)return[];const{data,error:requestError}=await supabase.from("guest_requests").select("id,reservation_id,request,request_type,department,priority,severity,escalation_status,status,created_at").in("reservation_id",ids).order("created_at",{ascending:false});if(requestError)throw requestError;return(data??[]).map((request)=>({...request,reservation:(reservations??[]).find((item)=>item.id===request.reservation_id)??null}))}
export async function getCustomerOverview(userId:string){const[financials,requests]=await Promise.all([getCustomerFinancials(userId),getCustomerRequests(userId)]);const groups=groupReservations(financials);const primary=groups.current[0]??groups.upcoming[0]??null;return{groups,primary,financial:primary,requests:requests.slice(0,3),notifications:buildNotifications(financials,requests).slice(0,4)}}
export function buildNotifications(financials:Awaited<ReturnType<typeof getCustomerFinancials>>,requests:Awaited<ReturnType<typeof getCustomerRequests>>){
 const items:{id:string;title:string;detail:string;createdAt:string;href:string}[]=[];
 for(const reservation of financials){items.push({id:`reservation-${reservation.id}`,title:`Reservation ${friendlyStatus(reservation.status)}`,detail:`${reservation.room_type} - ${reservation.confirmation_number??reservation.id}`,createdAt:String(reservation.invoice?.created_at??`${reservation.check_in}T00:00:00Z`),href:`/my-reservations/${reservation.id}`});for(const payment of reservation.payments){const title=payment.purpose==="reservation_deposit"?(payment.status==="paid"?"Reservation deposit verified":payment.status==="pending_verification"?"Deposit awaiting verification":`Reservation deposit ${friendlyStatus(payment.status)}`):`${friendlyStatus(payment.purpose)} ${friendlyStatus(payment.status)}`;items.push({id:`payment-${payment.id}`,title,detail:`${friendlyStatus(payment.method)} - ${reservation.confirmation_number??reservation.id}`,createdAt:String(payment.verified_at??payment.submitted_at??payment.created_at),href:"/account/payments"})}for(const refund of reservation.refunds)items.push({id:`refund-${refund.id}`,title:`Refund ${friendlyStatus(refund.status)}`,detail:`PHP ${Number(refund.eligible_amount).toLocaleString("en-PH")} - ${reservation.confirmation_number??reservation.id}`,createdAt:String(refund.processed_at??refund.created_at),href:"/account/payments"});for(const change of reservation.changeRequests)items.push({id:`change-${change.id}`,title:`Change request ${friendlyStatus(change.status)}`,detail:`${reservation.confirmation_number??reservation.id}`,createdAt:String(change.created_at),href:`/my-reservations/${reservation.id}`})}
 for(const request of requests)items.push({id:`request-${request.id}`,title:`Request ${friendlyStatus(request.status)}`,detail:request.request,createdAt:request.created_at,href:"/account/requests"});return items.sort((a,b)=>b.createdAt.localeCompare(a.createdAt));
}
export async function getCustomerReservationDetail(userId:string,id:string){
 if(!supabase)return null;await supabase.rpc("expire_booking_holds");
 const{data:reservation}=await supabase.from("reservations").select("id,confirmation_number,guest_id,guest_name,guest_email,room_type,room_number,check_in,check_out,guests,status,total,deposit,deposit_required,deposit_policy_snapshot,operational_policy_snapshot,payment_due_at,payment_status,payment_method,source,special_requests,request_options,transport_lines,expected_arrival,cancellation_reason,identity_status,created_at").eq("id",id).eq("user_id",userId).maybeSingle();if(!reservation)return null;
 const[{data:invoice},{data:guest},{data:refunds},{data:changeRequests}]=await Promise.all([supabase.from("invoices").select("id,amount,paid,balance,status,method,due_date").eq("reservation_id",id).maybeSingle(),reservation.guest_id?supabase.from("guests").select("name,email,phone,nationality,address").eq("id",reservation.guest_id).maybeSingle():Promise.resolve({data:null}),supabase.from("refund_requests").select("id,reason,paid_deposit,refund_basis_points,eligible_amount,status,reference,processed_at,created_at").eq("reservation_id",id).order("created_at",{ascending:false}),supabase.from("reservation_change_requests").select("id,requested_check_in,requested_check_out,requested_room_type,requested_guests,requested_special_requests,calculated_total,payment_difference,execution_status,reason,status,created_at").eq("reservation_id",id).order("created_at",{ascending:false})]);
 const [paymentResult,chargeResult]=invoice?await Promise.all([supabase.from("payments").select("id,amount,method,reference,purpose,status,submitted_at,verified_at,created_at").eq("invoice_id",invoice.id).order("created_at",{ascending:false}),supabase.from("folio_charges").select("id,description,category,amount,status,created_at").eq("invoice_id",invoice.id).order("created_at",{ascending:false})]):[{data:[]},{data:[]}];
 return{...reservation,invoice,guest,payments:paymentResult.data??[],charges:chargeResult.data??[],refunds:refunds??[],changeRequests:changeRequests??[],nights:calculateNights(reservation.check_in,reservation.check_out)};
}