import{readFileSync}from"node:fs";import{describe,expect,it}from"vitest";
const read=(path:string)=>readFileSync(path,"utf8");const migration=read("supabase/migrations/20260829041000_customer_guest_workflows.sql");const timezoneFix=read("supabase/migrations/20260829050000_hotel_timezone_modification_threshold.sql");const register=read("app/api/register/route.ts");const hold=read("app/api/booking/holds/route.ts");const profile=read("app/api/account/profile/route.ts");const request=read("app/api/account/requests/route.ts");const change=read("app/api/account/reservations/[id]/change-request/route.ts");const payment=read("app/api/account/reservations/[id]/payments/route.ts");const receipt=read("app/(booking)/(customer)/account/receipts/[id]/page.tsx");
// The migration's leading comment explains the `current_date` drift it fixes, so
// assertions about the SQL itself read from the first statement onward.
const timezoneSql=timezoneFix.slice(timezoneFix.indexOf("create or replace function"));
describe("customer identity and ownership controls",()=>{it("registers account and guest atomically without plaintext passwords",()=>{expect(register).toContain('bcrypt.hash(parsed.data.password,12)');expect(register).toContain('rpc("register_guest_account"');expect(migration).toContain("insert into user_accounts");expect(migration).toContain("insert into guests");expect(migration).not.toContain("p_password text")});it("requires guest role for booking and profile mutations",()=>{expect(hold).toContain('session.user.role!=="guest"');expect(profile).toContain('session.user.role!=="guest"');expect(profile).toContain('.is("user_account_id",null)')});it("scopes receipts through the owning reservation",()=>{expect(receipt).toContain('.eq("user_id",session.user.id)');expect(receipt).toContain('.eq("status","paid")')})});
describe("customer operational workflows",()=>{it("routes requests through an idempotent, ownership-checking RPC",()=>{expect(request).toContain('rpc("customer_submit_guest_request"');expect(migration).toContain("where id=p_reservation_id and user_id=p_user_id");expect(migration).toContain("r.status not in('confirmed','checked_in')");expect(migration).toContain("'stay_extension'")});it("keeps close-arrival changes behind Manager approval and Front Desk execution",()=>{expect(change).toContain('rpc("customer_request_reservation_change"');expect(migration).toContain("insert into manager_approval_requests");expect(migration).toContain("'reservation_modification'");expect(migration).toContain("'awaiting_execution'");expect(migration).toContain("manager_approval_sync_customer_change")});it("records manual stay payments as pending until authorized verification",()=>{expect(payment).toContain('rpc("customer_submit_stay_payment"');expect(migration).toContain("'stay_payment','pending_verification'");expect(migration).toContain("verify_customer_stay_payment");expect(migration).toContain("payments_manual_reference_unique")})});

describe("modification threshold uses the hotel's calendar day",()=>{
 it("measures days before arrival in the hotel timezone, not the UTC session date",()=>{expect(timezoneSql).toContain("today:=hotel_today(policy)");expect(timezoneSql).toContain("days_before:=r.check_in-today");expect(timezoneSql).not.toContain("current_date")});
 it("derives the day from the reservation's own policy snapshot",()=>{expect(timezoneSql).toContain("p_policy->>'hotelTimezone'");expect(timezoneSql.indexOf("policy:=coalesce(r.operational_policy_snapshot")).toBeLessThan(timezoneSql.indexOf("if cin<today"))});
 it("keeps the approval threshold and its escalation path intact",()=>{expect(timezoneSql).toContain("days_before>coalesce((policy->>'selfServiceModificationDays')::int,3)");expect(timezoneSql).toContain("insert into manager_approval_requests");expect(timezoneSql).toContain("'reservation_modification'")});
 it("changes only function definitions, never data or schema",()=>{for(const forbidden of ["drop table","truncate","delete from","alter table","drop column"])expect(timezoneFix.toLowerCase()).not.toContain(forbidden)});
 it("keeps the RPC callable only by the service role",()=>{expect(timezoneSql).toContain("revoke all on function public.hotel_today(jsonb) from public");expect(timezoneSql).toContain("grant execute on function public.hotel_today(jsonb) to service_role")});
});