import{describe,expect,it}from"vitest";import{cancellationRefund,DEFAULT_OPERATIONAL_POLICY,operationalPolicyFromSnapshot}from"@/lib/hotel-policy";
describe("provisional operational policy",()=>{it("uses configurable published defaults",()=>{expect(DEFAULT_OPERATIONAL_POLICY.cancellationFullRefundDays).toBe(14);expect(DEFAULT_OPERATIONAL_POLICY.cancellationPartialRefundDays).toBe(7);expect(DEFAULT_OPERATIONAL_POLICY.cancellationPartialRefundBasisPoints).toBe(5000);expect(DEFAULT_OPERATIONAL_POLICY.validIdRequired).toBe(true)});it("refunds the paid deposit, not the reservation total",()=>expect(cancellationRefund(6000,14,DEFAULT_OPERATIONAL_POLICY)).toEqual({basisPoints:10000,amount:6000}));it("calculates the 7 to 13 day partial tier",()=>expect(cancellationRefund(6000,10,DEFAULT_OPERATIONAL_POLICY)).toEqual({basisPoints:5000,amount:3000}));it("makes late cancellation and no-show deposits non-refundable",()=>{expect(cancellationRefund(6000,6,DEFAULT_OPERATIONAL_POLICY).amount).toBe(0);expect(cancellationRefund(6000,0,DEFAULT_OPERATIONAL_POLICY).amount).toBe(0)});it("preserves booking-time policy snapshots",()=>expect(operationalPolicyFromSnapshot({cancellationFullRefundDays:21}).cancellationFullRefundDays).toBe(21))});
describe("cancellation refund tier boundaries",()=>{
 it("treats the full-refund threshold as inclusive and the day before as partial",()=>{expect(cancellationRefund(6000,14,DEFAULT_OPERATIONAL_POLICY).basisPoints).toBe(10000);expect(cancellationRefund(6000,13,DEFAULT_OPERATIONAL_POLICY).basisPoints).toBe(5000)});
 it("treats the partial threshold as inclusive and the day before as non-refundable",()=>{expect(cancellationRefund(6000,7,DEFAULT_OPERATIONAL_POLICY).basisPoints).toBe(5000);expect(cancellationRefund(6000,6,DEFAULT_OPERATIONAL_POLICY).basisPoints).toBe(0)});
 it("refunds nothing once arrival has passed",()=>expect(cancellationRefund(6000,-2,DEFAULT_OPERATIONAL_POLICY)).toEqual({basisPoints:0,amount:0}));
 it("bases the refund on the amount actually paid, not the reservation total",()=>{expect(cancellationRefund(0,30,DEFAULT_OPERATIONAL_POLICY).amount).toBe(0);expect(cancellationRefund(2670,30,DEFAULT_OPERATIONAL_POLICY).amount).toBe(2670);expect(cancellationRefund(2670,10,DEFAULT_OPERATIONAL_POLICY).amount).toBe(1335)});
 it("rounds a partial refund to the centavo without floating point drift",()=>expect(cancellationRefund(100.01,10,DEFAULT_OPERATIONAL_POLICY).amount).toBe(50.01));
 it("honours a snapshot that widens the refund window over today's default",()=>{const snapshot=operationalPolicyFromSnapshot({cancellationFullRefundDays:21,cancellationPartialRefundDays:10});expect(cancellationRefund(6000,14,snapshot).basisPoints).toBe(5000);expect(cancellationRefund(6000,21,snapshot).basisPoints).toBe(10000);expect(cancellationRefund(6000,9,snapshot).basisPoints).toBe(0)})});
