import{readFileSync}from"node:fs";import{describe,expect,it}from"vitest";import{canPerformHousekeeping,canReportHousekeepingMaintenance}from"@/lib/permissions";
const read=(path:string)=>readFileSync(path,"utf8");const migration=read("supabase/migrations/20260830010000_housekeeping_operational_workflow.sql");const resources=read("app/api/resources/[resource]/route.ts");const dashboard=read("components/manager/manager-dashboard-client.tsx");const staffData=read("lib/staff-data.ts");const lockdown=read("supabase/migrations/20260830030000_lock_rpc_execute_to_service_role.sql");const nullSafe=read("supabase/migrations/20260830040000_null_safe_actor_role_guards.sql");
describe("authoritative Housekeeping lifecycle",()=>{
 it("turns checkout into one source-linked dirty-room turnover",()=>{expect(migration).toContain("source_type,source_id");expect(migration).toContain("'checkout_cleaning'");expect(migration).toContain("'checkout',r.id");expect(migration).toContain("status='dirty',housekeeping='dirty'");expect(migration).toContain("on conflict do nothing")});
 it("starts work exclusively and transactionally",()=>{expect(migration).toContain("housekeeping_one_exclusive_active_per_room");expect(migration).toContain("where status='in_progress'");expect(migration).toContain("pg_advisory_xact_lock");expect(migration).toContain("housekeeping='cleaning'");expect(migration).toContain("TASK_ASSIGNED_TO_ANOTHER_WORKER")});
 it("assigns and reassigns through a protected workflow without erasing ownership history",()=>{expect(migration).toContain("housekeeping_task_assignments");expect(migration).toContain("housekeeping_assign_task");expect(migration).toContain("SELF_ASSIGNMENT_ONLY");expect(migration).toContain("previous_user_id");expect(migration).toContain("housekeeping_reassign_task")});
 it("requires completion before inspection and readiness",()=>{expect(migration).toContain("if t.status<>'in_progress'then raise exception'TASK_NOT_COMPLETABLE'");expect(migration).toContain("housekeeping_inspection_required");expect(migration).toContain("inspection_status='pending'");expect(migration).toContain("ROOM_NOT_VACANT_FOR_READINESS");expect(migration).toContain("when blocked then'maintenance'")});
 it("creates a reclean task after failed inspection without rewriting history",()=>{expect(migration).toContain("'Reclean after failed inspection'");expect(migration).toContain("'reclean_required'");expect(migration).toContain("parent_task_id");expect(migration).not.toContain("delete from housekeeping_tasks")});
 it("keeps stayover service occupancy-safe and supports DND or refusal deferral",()=>{expect(migration).toContain("STAYOVER_REQUIRES_OCCUPIED_ROOM");expect(migration).toContain("room.status='occupied'then'clean'");expect(migration).toContain("CHECKOUT_CLEANING_NOT_DEFERRABLE");expect(migration).toContain("deferred_reason")});
 it("links guest requests, room assignment, and maintenance cleanup",()=>{expect(migration).toContain("create_housekeeping_task_for_guest_request");expect(migration).toContain("link_housekeeping_tasks_to_assigned_room");expect(migration).toContain("housekeeping_report_maintenance");expect(migration).toContain("'maintenance_cleanup'");expect(migration).toContain("housekeeping_task_id")});
});
describe("Housekeeping least privilege and interface",()=>{
 it("allows only Owner, Admin, and Housekeeping to execute room-care work",()=>{for(const role of["owner","admin","housekeeping"]as const){expect(canPerformHousekeeping(role)).toBe(true);expect(canReportHousekeepingMaintenance(role)).toBe(true)}for(const role of["manager","front_desk","maintenance","accounting","guest"]as const)expect(canPerformHousekeeping(role)).toBe(false);expect(migration).toContain("actor not in('owner','admin','housekeeping')")});
 it("blocks direct task, room, and guest-request mutation by Housekeeping",()=>{expect(resources).toContain('["payments","refunds","housekeeping_tasks"].includes(resource)');expect(resources).toContain('role==="housekeeping"&&["rooms","guest_requests","housekeeping_tasks"].includes(resource)')});
 it("shows real operational context without guest contact or financial fields",()=>{for(const field of["room_housekeeping","maintenance_blocked","next_arrival","inspection_status"])expect(staffData).toContain(field);const section=staffData.slice(staffData.indexOf('if (resource === "housekeeping_tasks")'),staffData.indexOf('if (resource === "payments")'));for(const forbidden of["guest_email","guest_phone","balance","deposit"])expect(section).not.toContain(forbidden)});
 it("exposes explicit workflow actions and keeps Manager coordination separate",()=>{for(const action of["Claim",">Start<",">Complete<",">Inspect<",">Defer<","Report issue","Prioritize"])expect(dashboard).toContain(action);expect(dashboard).toContain('canHousekeep={["owner","admin","housekeeping"].includes(user.role)}');expect(dashboard).toContain("Housekeeping remains responsible for completion")});
});
describe("privileged RPC hardening",()=>{
 it("strips every anon and authenticated privilege, leaving service_role untouched",()=>{expect(lockdown).toContain("revoke execute on all functions in schema public from anon, authenticated");expect(lockdown).toContain("alter default privileges in schema public revoke execute on functions from anon, authenticated");expect(lockdown).toContain("revoke all on all tables in schema public from anon, authenticated");expect(lockdown).not.toContain("from service_role")});
 it("makes the actor role guard reject a null role instead of falling through",()=>{expect(nullSafe).toContain("'if actor not in(', 'if actor is null or actor not in('");expect(nullSafe).toContain("'if target_role<>', 'if target_role is null or target_role<>'");expect(nullSafe).toContain("NULL_UNSAFE_ACTOR_GUARD_REMAINS")});
 it("rewrites guards without dropping or re-signing any function",()=>{expect(nullSafe).toContain("pg_get_functiondef");for(const forbidden of["drop function","drop table","truncate","delete from"])expect(nullSafe.toLowerCase()).not.toContain(forbidden)});
 it("skips already-patched bodies so the migration is safe to re-run",()=>{expect(nullSafe).toContain("prosrc not like '%actor is null or actor not in(%'");expect(nullSafe).toContain("prosrc not like '%target_role is null or target_role<>%'")});
 it("keeps every privileged Housekeeping RPC gated on an active account",()=>{for(const rpc of["housekeeping_assign_task","housekeeping_start_task","housekeeping_complete_task","housekeeping_inspect_task","housekeeping_defer_task","housekeeping_report_maintenance"]){const body=migration.slice(migration.indexOf(`function public.${rpc}(`));expect(body.slice(0,body.indexOf("end$$"))).toContain("from user_accounts ua where ua.id=p_staff_user_id and ua.active")}});
});
