import{readFileSync}from"node:fs";import{describe,expect,it}from"vitest";import{MANAGER_APPROVAL_TYPES}from"@/lib/manager";
// Stay extension (extra nights — checkout DATE changes) as a first-class workflow:
// normal path first, Manager exception only when the normal path refuses, and one
// single extension implementation underneath both.
const migration=readFileSync("supabase/migrations/20260923010000_stay_extension_exception.sql","utf8");
const extendMigration=readFileSync("supabase/migrations/20260829020000_accounting_operations_rpcs.sql","utf8");
const dashboard=readFileSync("components/manager/manager-dashboard-client.tsx","utf8");
const dialog=readFileSync("components/manager/extend-stay-dialog.tsx","utf8");
const approvalsRoute=readFileSync("app/api/manager/approvals/route.ts","utf8");
const executeRoute=readFileSync("app/api/manager/approvals/[id]/execute/route.ts","utf8");
const extendRoute=readFileSync("app/api/front-desk/reservations/[id]/extend/route.ts","utf8");
const previewRoute=readFileSync("app/api/front-desk/reservations/[id]/extend-preview/route.ts","utf8");
const approvalDisplay=readFileSync("lib/approval-display.ts","utf8");
describe("stay_extension exception type",()=>{it("is an allowed approval type everywhere the type list is defined",()=>{expect(MANAGER_APPROVAL_TYPES).toContain("stay_extension");expect(migration).toContain("'stay_extension'");expect(dashboard).toContain('"stay_extension"')});it("requires an in-house reservation and a later checkout at request time",()=>{expect(migration).toContain("STAY_EXTENSION_REQUIRES_IN_HOUSE");expect(migration).toContain("STAY_EXTENSION_INVALID_DATE");expect(approvalsRoute).toContain('value.type==="stay_extension"');expect(approvalsRoute).toContain("requestedCheckOut")});it("stamps the server-computed extension snapshot and strips any client-supplied one",()=>{expect(migration).toContain("p_requested_action-'stayExtension'");expect(migration).toContain("jsonb_build_object('stayExtension'");for(const key of["currentCheckOut","requestedCheckOut","nights","rate","additionalAmount","projectedTotal","roomConflict","roomNumber","roomType"])expect(migration).toContain(`'${key}'`);expect(approvalDisplay).toContain('"stayExtension"')});it("is approvable only in-house with a valid stamp — a room conflict does not block approval",()=>{expect(migration).toContain("a.request_type='stay_extension'");expect(migration).toContain("a.requested_action->'stayExtension'is null")});it("keeps pricing on the existing rule: current room-type base_rate × added nights",()=>{expect(migration).toContain("v_type.base_rate*(v_new_out-r.check_out)");expect(migration).not.toContain("extension_rate")})});
describe("one extension implementation",()=>{it("executes by performing front_desk_extend_stay with the approval id as idempotency key",()=>{expect(migration).toContain("perform public.front_desk_extend_stay(r.id,v_new_out,a.reason,a.id,p_staff_user_id)");expect(migration).not.toMatch(/insert into folio_charges[^;]*category'extension'/)});it("allows only a same-type room move at execution, revalidating everything",()=>{expect(migration).toContain("EXTENSION_ROOM_NOT_READY");expect(migration).toContain("EXTENSION_ROOM_UNAVAILABLE");expect(migration).toContain("newroom.type<>r.room_type");expect(executeRoute).toContain("EXTENSION_ROOM_NOT_READY");expect(executeRoute).toContain("EXTENSION_ROOM_UNAVAILABLE")});it("keeps the normal path unchanged and front-desk guarded",()=>{expect(extendRoute).toContain('new Set(["front_desk"])');expect(extendRoute).toContain("EXTENSION_REQUIRES_ROOM_CHANGE")})});
describe("server-previewed Extend stay dialog",()=>{it("derives every figure from the preview RPC, never client-side arithmetic",()=>{expect(dialog).toContain("/extend-preview?checkOut=");expect(dialog).not.toMatch(/rate\s*\*/);expect(dialog).not.toMatch(/base_rate/)});it("submits the normal extension first, with an idempotency key",()=>{expect(dialog).toContain("/extend");expect(dialog).toContain("idempotencyKey");expect(dialog).toContain('crypto.randomUUID()')});it("hands off to the stay_extension Manager exception when the room conflicts",()=>{expect(dialog).toContain("conflicts with a future stay");expect(dialog).toContain("stay_extension");expect(dialog).toContain("requestedCheckOut")});it("flags departure transportation on the old checkout date without rescheduling it",()=>{expect(dialog).toContain("not rescheduled automatically");expect(dialog).not.toContain("/transportation")});it("guards the preview endpoint to Front Desk server-side",()=>{expect(previewRoute).toContain('new Set(["front_desk"])');expect(previewRoute).toContain("front_desk_extend_stay_preview");expect(previewRoute).toContain("403")})});
describe("Manager review and execution UI",()=>{it("groups stay_extension under Operational and lets Front Desk execute it",()=>{expect(dashboard).toContain('"late_checkout", "stay_extension"');expect(dashboard).toContain('"checkout_exception","stay_extension"')});it("clarifies the dropdown labels so extension and late checkout are never confused",()=>{for(const text of["Room type change (mid-stay)","Stay extension (extra nights)","Late checkout (same day)","Checkout exception (folio override)"])expect(dashboard).toContain(text)});it("prompts for a same-type room when execution hits a room conflict",()=>{expect(dashboard).toContain("conflicts with the extended stay");expect(dashboard).toContain("Same-type room move required")});it("renders the server-stamped stayExtension snapshot in the review modal",()=>{expect(dashboard).toContain("isStayExtension");expect(dashboard).toContain("Stay extension")})});
describe("the normal path is unchanged",()=>{it("front_desk_extend_stay still charges through the folio with its own gates",()=>{expect(extendMigration).toContain("front_desk_extend_stay");expect(extendMigration).toContain("EXTENSION_REQUIRES_ROOM_CHANGE");expect(extendMigration).toContain("'extension'")})});
