import{NextResponse}from"next/server";import{z}from"zod";import{canReconcileFinancials}from"@/lib/permissions";import{guardFailed,guardFinancial,invalid,rpcFailure}from"@/lib/financial-route";
// settledAmount is the operator-entered figure from an external statement. It is recorded as a
// manual reconciliation input only - it never marks a payment settled or provider-verified.
const schema=z.object({periodStart:z.string().regex(/^\d{4}-\d{2}-\d{2}$/),periodEnd:z.string().regex(/^\d{4}-\d{2}-\d{2}$/),method:z.string().trim().min(2).max(40),settledAmount:z.coerce.number().min(0).max(1000000000),notes:z.string().trim().max(400).optional(),idempotencyKey:z.string().uuid()});
export async function POST(request:Request){const context=await guardFinancial(canReconcileFinancials,"Accounting authorization required.");if(guardFailed(context))return context;
 const parsed=schema.safeParse(await request.json().catch(()=>null));if(!parsed.success)return invalid(parsed.error?.issues[0]?.message??"Invalid reconciliation.");
 const{data,error}=await context.client.rpc("accounting_reconcile_payments",{p_period_start:parsed.data.periodStart,p_period_end:parsed.data.periodEnd,p_method:parsed.data.method,p_settled_amount:parsed.data.settledAmount,p_notes:parsed.data.notes??null,p_idempotency_key:parsed.data.idempotencyKey,p_staff_user_id:context.actorId});
 if(error)return rpcFailure(error,{INVALID_RECONCILIATION_PERIOD:"The reconciliation period is invalid.",PAYMENT_METHOD_REQUIRED:"A payment method is required.",INVALID_SETTLED_AMOUNT:"The settled amount cannot be negative.",VARIANCE_EXPLANATION_REQUIRED:"A variance must be explained before it can be recorded.",RECONCILIATION_FORBIDDEN:"Accounting authorization required."},"Unable to record this reconciliation.");
 return NextResponse.json({data})}
