import Link from "next/link";
import { ArrowRight, Bell, BookOpenText, CalendarDays, Compass, ReceiptText } from "lucide-react";
import { requireCustomerSession } from "@/lib/customer-auth";
import { calculateFinancialState, calculateNights, formatPeso } from "@/lib/booking";
import { formatStayRange, friendlyStatus, getCustomerOverview } from "@/lib/customer";

export default async function CustomerOverviewPage(){
  const session=await requireCustomerSession();const data=await getCustomerOverview(session.user.id);const stay=data.primary;const financial=data.financial;
  const money=stay?calculateFinancialState(financial?.invoice?.amount??stay.total,financial?.invoice?.paid??stay.deposit??0):null;
  return <><section className="customer-page-title"><p className="eyebrow">Your Haven</p><h1>Welcome back, {(session.user.name??"Guest").split(" ")[0]}.</h1><p>Everything you need for your next stay, gathered in one calm place.</p></section>
  {stay?<section className="customer-feature-card"><div><span className={`customer-status ${stay.status}`}>{friendlyStatus(stay.status)}</span><p>{stay.status==="pending"?"Awaiting deposit verification":data.groups.current.length?"Current stay":"Upcoming stay"}</p><h2>{stay.room_type}</h2><strong>{formatStayRange(stay.check_in,stay.check_out)}</strong><small>{calculateNights(stay.check_in,stay.check_out)} nights · {stay.guests} guest{stay.guests!==1?"s":""} · {stay.confirmation_number??stay.id}</small></div><div><Link className="btn btn-cream" href={`/my-reservations/${stay.id}`}>Manage stay <ArrowRight size={15}/></Link></div></section>:<section className="customer-feature-card empty-feature"><div><p>No upcoming stay</p><h2>Let&apos;s plan something memorable.</h2></div><Link className="btn btn-cream" href="/account/find-room">Find a room</Link></section>}
  <section className="customer-overview-grid"><article className="customer-card"><div className="customer-card-heading"><ReceiptText/><div><p>Remaining balance</p><h2>{money?formatPeso(money.balance):"—"}</h2></div></div>{stay&&money?<><dl><div><dt>Stay total</dt><dd>{formatPeso(money.total)}</dd></div><div><dt>Required deposit</dt><dd>{formatPeso(stay.deposit_required??0)}</dd></div><div><dt>Paid</dt><dd>{formatPeso(money.paid)}</dd></div><div><dt>Payment status</dt><dd>{friendlyStatus(financial?.invoice?.status??stay.payment_status)}</dd></div></dl><Link href="/account/payments">View payment details <ArrowRight size={14}/></Link></>:<p>No reservation balance to display.</p>}</article>
  <article className="customer-card"><div className="customer-card-heading"><BookOpenText/><div><p>Guest requests</p><h2>{data.requests.length} recent</h2></div></div>{data.requests.length?<ul>{data.requests.map((request)=><li key={request.id}><span>{request.request}</span><b>{friendlyStatus(request.status)}</b></li>)}</ul>:<p>No active or recent requests.</p>}<Link href="/account/requests">View requests <ArrowRight size={14}/></Link></article>
  <article className="customer-card customer-notification-preview"><div className="customer-card-heading"><Bell/><div><p>Notifications</p><h2>Recent updates</h2></div></div>{data.notifications.length?<ul>{data.notifications.slice(0,3).map((item)=><li key={item.id}><Link href={item.href}>{item.title}<small>{item.detail}</small></Link></li>)}</ul>:<p>No updates yet.</p>}<Link href="/account/notifications">View notifications <ArrowRight size={14}/></Link></article></section>
  <section className="customer-quick-actions"><h2>Quick actions</h2><div><Link href="/account/find-room"><Compass/>Find a room</Link><Link href="/my-reservations"><CalendarDays/>My reservations</Link><Link href="/account/requests"><BookOpenText/>Guest requests</Link><Link href="/account/payments"><ReceiptText/>Payments</Link></div></section></>;
}
