import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowLeft, BookOpenText, ReceiptText } from "lucide-react";
import { ReservationActions } from "@/components/customer/reservation-actions";
import { requireCustomerSession } from "@/lib/customer-auth";
import { formatPeso, transportTotal } from "@/lib/booking";
import { formatStayDate, formatStayRange, friendlyStatus, getCustomerReservationDetail } from "@/lib/customer";
import { displayTime, operationalPolicyFromSnapshot } from "@/lib/hotel-policy";

export default async function ReservationPage({params}:{params:Promise<{id:string}>}){
 const session=await requireCustomerSession();const{id}=await params;const reservation=await getCustomerReservationDetail(session.user.id,id);if(!reservation)notFound();
 const invoice=reservation.invoice;const stayTotal=Number(reservation.total||0);const folioTotal=Number(invoice?.amount??stayTotal);const paid=Number(invoice?.paid??reservation.deposit??0);const balance=Number(invoice?.balance??Math.max(folioTotal-paid,0));const nightly=reservation.nights?stayTotal/reservation.nights:stayTotal;const policy=operationalPolicyFromSnapshot(reservation.operational_policy_snapshot);
 return <><section className="customer-page-title split"><div><Link className="customer-back" href="/my-reservations"><ArrowLeft size={14}/>All reservations</Link><p className="eyebrow">{reservation.confirmation_number??reservation.id}</p><h1>{reservation.room_type}</h1><p>{formatStayRange(reservation.check_in,reservation.check_out)}</p></div><div className="customer-title-status"><span className={`customer-status ${reservation.status}`}>{friendlyStatus(reservation.status)}</span><span className={`customer-status ${invoice?.status??reservation.payment_status}`}>{friendlyStatus(invoice?.status??reservation.payment_status)}</span></div></section>
 <ReservationActions id={reservation.id} status={reservation.status}/>
 <div className="customer-detail-grid"><section className="customer-detail-card"><h2>Stay details</h2><dl><div><dt>Check-in</dt><dd>{formatStayDate(reservation.check_in)} - from {displayTime(policy.checkInTime)}</dd></div><div><dt>Check-out</dt><dd>{formatStayDate(reservation.check_out)} - by {displayTime(policy.checkOutTime)}</dd></div><div><dt>Nights</dt><dd>{reservation.nights}</dd></div><div><dt>Guests</dt><dd>{reservation.guests}</dd></div><div><dt>Guest</dt><dd>{reservation.guest?.name??reservation.guest_name}</dd></div><div><dt>Email</dt><dd>{reservation.guest?.email??reservation.guest_email??"-"}</dd></div><div><dt>Mobile</dt><dd>{reservation.guest?.phone??"-"}</dd></div><div><dt>Physical room</dt><dd>{["checked_in","checked_out"].includes(reservation.status)&&reservation.room_number?reservation.room_number:"Assigned by Front Desk when operationally appropriate"}</dd></div><div><dt>Identity check</dt><dd>{friendlyStatus(reservation.identity_status)}</dd></div><div><dt>Booking source</dt><dd>{friendlyStatus(reservation.source)}</dd></div></dl>{reservation.special_requests&&<div className="customer-special-request"><strong>Special requests</strong><p>{reservation.special_requests}</p></div>}{(()=>{const raw:unknown=reservation.transport_lines;const transport=(Array.isArray(raw)?raw:[]).filter((line):line is {name:string;price:number|string;note?:string|null}=>line!==null&&typeof line==="object"&&Number((line as{price?:unknown}).price??0)>0);return transport.length>0&&<div className="customer-special-request"><strong>Hotel transport</strong><p>{transport.map((line)=><span key={line.name}>{line.name} · {formatPeso(Number(line.price))}</span>)}<small className="summary-note">Included in your stay total above and covered by the reservation deposit. Total {formatPeso(transportTotal(transport))}.</small></p></div>;})()}{reservation.cancellation_reason&&<div className="customer-special-request"><strong>Cancellation / closure note</strong><p>{reservation.cancellation_reason}</p></div>}</section>
 <section className="customer-detail-card"><h2>Rate & folio</h2><dl><div><dt>Nightly rate x {reservation.nights}</dt><dd>{formatPeso(nightly*reservation.nights)}</dd></div><div><dt>Original stay total</dt><dd>{formatPeso(stayTotal)}</dd></div><div><dt>Current folio total</dt><dd>{formatPeso(folioTotal)}</dd></div><div><dt>Required reservation deposit</dt><dd>{formatPeso(reservation.deposit_required??0)}</dd></div><div><dt>Net payments received</dt><dd>{formatPeso(paid)}</dd></div><div className="detail-balance"><dt>Remaining balance</dt><dd>{formatPeso(balance)}</dd></div></dl>
 {reservation.charges.length>0&&<div className="reservation-payment-list"><h3>Folio charges</h3>{reservation.charges.map((charge)=><p key={charge.id}><span>{charge.description} - {friendlyStatus(charge.category)}</span><span>{formatPeso(charge.amount)}</span></p>)}</div>}
 {reservation.payments.length>0&&<div className="reservation-payment-list"><h3>Transactions</h3>{reservation.payments.map((payment)=><p key={payment.id}><span>{friendlyStatus(payment.purpose)} - {friendlyStatus(payment.method)}</span><span>{payment.purpose==="refund"?"-":""}{formatPeso(payment.amount)} - {friendlyStatus(payment.status)}{payment.status==="paid"&&<> · <Link href={`/account/receipts/${payment.id}`}>Receipt</Link></>}</span></p>)}</div>}
 {reservation.refunds.length>0&&<div className="reservation-payment-list"><h3>Refund requests</h3>{reservation.refunds.map((refund)=><p key={refund.id}><span>{refund.reason}</span><span>{formatPeso(refund.eligible_amount)} - {friendlyStatus(refund.status)}</span></p>)}</div>}
 {reservation.changeRequests.length>0&&<div className="reservation-payment-list"><h3>Change requests</h3>{reservation.changeRequests.map((request)=><p key={request.id}><span>{request.reason}</span><span>{friendlyStatus(request.status)}</span></p>)}</div>}
 <Link className="customer-inline-action" href="/account/payments"><ReceiptText size={15}/>View payments & folio</Link><Link className="customer-inline-action" href="/account/requests"><BookOpenText size={15}/>Submit a guest request</Link></section></div>
 <section className="customer-policy"><h2>Policy accepted with this reservation</h2><p>{reservation.status==="pending"?"This reservation is awaiting deposit verification and is not yet confirmed. ":""}Valid government ID is {policy.validIdRequired?"required":"not required by the current configuration"} at check-in. The remaining balance and incidental charges are due {policy.incidentalsDue.toLowerCase()}. Deposit refund: 100% at least {policy.cancellationFullRefundDays} days before arrival, {policy.cancellationPartialRefundBasisPoints/100}% at least {policy.cancellationPartialRefundDays} days before arrival, otherwise non-refundable. Special requests are recorded but {policy.specialRequestsGuaranteed?"guaranteed":"not guaranteed"}.</p></section></>
}