-- System Administrator formalization (Q1): hotel timezone is system/operational
-- configuration, so Owner OR Admin may change it. Removes the Owner-only
-- timezone gate from admin_update_operational_policy.
-- Everything else is the live body, unchanged: Owner/Admin authority,
-- version-stale protection, IANA timezone validation, required reason,
-- audited before/after, future-only snapshots.

create or replace function public.admin_update_operational_policy(p_hotel_timezone text,p_check_in_time time,p_check_out_time time,p_no_show_cutoff_time time,p_valid_id_required boolean,p_minimum_booking_age integer,p_cancellation_full_refund_days integer,p_cancellation_partial_refund_days integer,p_cancellation_partial_refund_basis_points integer,p_self_service_modification_days integer,p_early_check_in_allowed boolean,p_housekeeping_inspection_required boolean,p_deposit_sla_hours integer,p_vat_rate_bp integer,p_service_charge_bp integer,p_reason text,p_expected_version integer,p_actor_user_id uuid)
returns jsonb language plpgsql security definer set search_path=public as $$declare actor text;p hotel_operational_policies%rowtype;begin
 select role into actor from user_accounts where id=p_actor_user_id and active;if actor is null or actor not in('owner','admin')then raise exception'ADMIN_AUTHORITY_REQUIRED';end if;select * into p from hotel_operational_policies where key='default'for update;if not found then raise exception'POLICY_NOT_FOUND';end if;if p.version<>p_expected_version then raise exception'POLICY_STALE';end if;if not exists(select 1 from pg_timezone_names where name=p_hotel_timezone)or p_minimum_booking_age not between 1 and 120 or p_cancellation_full_refund_days<0 or p_cancellation_partial_refund_days<0 or p_cancellation_full_refund_days<p_cancellation_partial_refund_days or p_cancellation_partial_refund_basis_points not between 0 and 10000 or p_self_service_modification_days<0 or p_deposit_sla_hours is null or p_deposit_sla_hours not between 0 and 72 or p_vat_rate_bp is null or p_vat_rate_bp not between 0 and 10000 or p_service_charge_bp is null or p_service_charge_bp not between 0 and 10000 or nullif(trim(p_reason),'')is null then raise exception'INVALID_OPERATIONAL_POLICY';end if;
 update hotel_operational_policies set hotel_timezone=p_hotel_timezone,check_in_time=p_check_in_time,check_out_time=p_check_out_time,no_show_cutoff_time=p_no_show_cutoff_time,valid_id_required=p_valid_id_required,minimum_booking_age=p_minimum_booking_age,cancellation_full_refund_days=p_cancellation_full_refund_days,cancellation_partial_refund_days=p_cancellation_partial_refund_days,cancellation_partial_refund_basis_points=p_cancellation_partial_refund_basis_points,self_service_modification_days=p_self_service_modification_days,early_check_in_allowed=p_early_check_in_allowed,housekeeping_inspection_required=p_housekeeping_inspection_required,deposit_sla_hours=p_deposit_sla_hours,vat_rate_bp=p_vat_rate_bp,service_charge_bp=p_service_charge_bp,version=version+1,updated_at=now()where key='default';insert into audit_logs(user_id,action,entity_type,entity_id,before_data,after_data)values(p_actor_user_id,'admin_update_operational_policy','hotel_operational_policy','default',to_jsonb(p),jsonb_build_object('hotelTimezone',p_hotel_timezone,'checkInTime',p_check_in_time,'checkOutTime',p_check_out_time,'noShowCutoffTime',p_no_show_cutoff_time,'validIdRequired',p_valid_id_required,'minimumBookingAge',p_minimum_booking_age,'cancellationFullRefundDays',p_cancellation_full_refund_days,'cancellationPartialRefundDays',p_cancellation_partial_refund_days,'cancellationPartialRefundBasisPoints',p_cancellation_partial_refund_basis_points,'selfServiceModificationDays',p_self_service_modification_days,'earlyCheckInAllowed',p_early_check_in_allowed,'housekeepingInspectionRequired',p_housekeeping_inspection_required,'depositSlaHours',p_deposit_sla_hours,'vatRateBp',p_vat_rate_bp,'serviceChargeBp',p_service_charge_bp,'reason',trim(p_reason),'version',p.version+1));return jsonb_build_object('version',p.version+1);end$$;

revoke all on function public.admin_update_operational_policy(text,time,time,time,boolean,integer,integer,integer,integer,integer,boolean,boolean,integer,integer,integer,text,integer,uuid)from public,anon,authenticated;
-- Supabase grants anon/authenticated named-role EXECUTE that a PUBLIC revoke misses;
-- revoke them explicitly (service_role keeps EXECUTE below).
revoke execute on function public.admin_update_operational_policy(text,time,time,time,boolean,integer,integer,integer,integer,integer,boolean,boolean,integer,integer,integer,text,integer,uuid)from anon,authenticated;
grant execute on function public.admin_update_operational_policy(text,time,time,time,boolean,integer,integer,integer,integer,integer,boolean,boolean,integer,integer,integer,text,integer,uuid)to service_role;
