-- Manager / Operations Manager approvals and escalations.
alter table public.hotel_operational_policies add column if not exists manager_arrival_risk_minutes integer not null default 120 check(manager_arrival_risk_minutes between 15 and 1440);
alter table public.hotel_operational_policies add column if not exists guest_request_overdue_minutes integer not null default 60 check(guest_request_overdue_minutes between 15 and 10080);
alter table public.hotel_operational_policies add column if not exists housekeeping_turnover_overdue_minutes integer not null default 180 check(housekeeping_turnover_overdue_minutes between 15 and 10080);
create table if not exists public.manager_approval_requests(
 id uuid primary key default gen_random_uuid(),request_type text not null check(request_type in('room_upgrade','reservation_modification','early_check_in','late_checkout','guest_compensation','refund_exception','checkout_exception','guest_escalation')),
 related_entity_type text not null,related_entity_id text not null,reservation_id text references public.reservations(id)on delete restrict,guest_request_id uuid references public.guest_requests(id)on delete restrict,
 department text not null,severity text not null default 'normal'check(severity in('normal','high','critical')),reason text not null,requested_action jsonb not null default'{}',normal_policy_result jsonb not null default'{}',
 requested_by uuid not null references public.user_accounts(id)on delete restrict,requested_at timestamptz not null default now(),status text not null default'pending'check(status in('pending','approved','rejected','cancelled','expired')),
 reviewed_by uuid references public.user_accounts(id)on delete set null,reviewed_at timestamptz,decision_reason text,execution_status text not null default'pending_review'check(execution_status in('pending_review','awaiting_execution','executed','not_required','cancelled')),
 executed_by uuid references public.user_accounts(id)on delete set null,executed_at timestamptz,version integer not null default 1,updated_at timestamptz not null default now());
create unique index if not exists manager_approval_one_pending on public.manager_approval_requests(request_type,related_entity_type,related_entity_id)where status='pending';
create index if not exists manager_approval_queue_idx on public.manager_approval_requests(status,severity,requested_at desc);
create table if not exists public.manager_notes(id uuid primary key default gen_random_uuid(),approval_id uuid not null references public.manager_approval_requests(id)on delete restrict,note text not null,created_by uuid references public.user_accounts(id)on delete set null,created_at timestamptz not null default now());
alter table public.guest_requests add column if not exists severity text not null default'normal';
alter table public.guest_requests add column if not exists due_at timestamptz;
alter table public.guest_requests add column if not exists escalation_status text not null default'none';
alter table public.guest_requests add column if not exists escalated_by uuid references public.user_accounts(id)on delete set null;
alter table public.guest_requests add column if not exists escalated_at timestamptz;
alter table public.guest_requests add column if not exists manager_resolution text;
alter table public.guest_requests drop constraint if exists guest_requests_severity_check;
alter table public.guest_requests add constraint guest_requests_severity_check check(severity in('normal','high','critical'));
alter table public.guest_requests drop constraint if exists guest_requests_escalation_status_check;
alter table public.guest_requests add constraint guest_requests_escalation_status_check check(escalation_status in('none','escalated','coordinated','resolved'));
alter table public.reservations add column if not exists early_check_in_approved_until timestamptz;
alter table public.reservations add column if not exists late_checkout_until timestamptz;
alter table public.refund_requests add column if not exists exception_approval_id uuid references public.manager_approval_requests(id)on delete restrict;
alter table public.refund_requests add column if not exists normal_policy_amount numeric(12,2)not null default 0 check(normal_policy_amount>=0);
alter table public.financial_adjustments add column if not exists manager_approval_id uuid references public.manager_approval_requests(id)on delete restrict;
create unique index if not exists financial_adjustments_manager_approval_unique on public.financial_adjustments(manager_approval_id)where manager_approval_id is not null;
drop index if exists public.refund_requests_open_unique;
create unique index if not exists refund_requests_normal_open_unique on public.refund_requests(reservation_id)where status='pending'and exception_approval_id is null;
create unique index if not exists refund_requests_exception_unique on public.refund_requests(exception_approval_id)where exception_approval_id is not null;
alter table public.manager_approval_requests enable row level security;alter table public.manager_notes enable row level security;
revoke all on table public.manager_approval_requests,public.manager_notes from anon,authenticated;

create or replace function public.request_manager_approval(p_request_type text,p_related_entity_type text,p_related_entity_id text,p_reservation_id text,p_guest_request_id uuid,p_department text,p_severity text,p_reason text,p_requested_action jsonb,p_staff_user_id uuid)
returns uuid language plpgsql security definer set search_path=public as $$
declare actor text;r reservations%rowtype;g guest_requests%rowtype;aid uuid;normal_result jsonb:='{}';policy jsonb;deposit_paid numeric;normal_refund numeric;begin
select role into actor from user_accounts where id=p_staff_user_id and active;if actor not in('owner','admin','front_desk','housekeeping','maintenance','accounting')then raise exception'APPROVAL_REQUEST_FORBIDDEN';end if;
if p_request_type not in('room_upgrade','reservation_modification','early_check_in','late_checkout','guest_compensation','refund_exception','checkout_exception','guest_escalation')or nullif(trim(p_reason),'')is null then raise exception'INVALID_APPROVAL_REQUEST';end if;
if p_severity not in('normal','high','critical')then raise exception'INVALID_SEVERITY';end if;
if p_request_type<>'guest_escalation'and p_reservation_id is null then raise exception'RESERVATION_REQUIRED';end if;
if p_reservation_id is not null then select * into r from reservations where id=p_reservation_id;if not found then raise exception'RESERVATION_NOT_FOUND';end if;policy:=coalesce(r.operational_policy_snapshot,current_operational_policy_snapshot());
 normal_result:=jsonb_build_object('reservationStatus',r.status,'roomType',r.room_type,'checkIn',r.check_in,'checkOut',r.check_out,'policySnapshot',policy);end if;
if p_request_type='guest_escalation'then select * into g from guest_requests where id=p_guest_request_id for update;if not found or g.status='completed'then raise exception'GUEST_REQUEST_NOT_ESCALATABLE';end if;
 update guest_requests set severity=p_severity,escalation_status='escalated',escalated_by=p_staff_user_id,escalated_at=now()where id=g.id;end if;
if p_request_type='refund_exception'then
 if r.status not in('cancelled','no_show')then raise exception'REFUND_EXCEPTION_REQUIRES_CLOSURE';end if;
 select coalesce(sum(amount),0)into deposit_paid from payments where reservation_id=r.id and purpose='reservation_deposit'and status='paid';
 select coalesce(max(eligible_amount),0)into normal_refund from refund_requests where reservation_id=r.id and exception_approval_id is null;
 normal_result:=normal_result||jsonb_build_object('settledDeposit',deposit_paid,'normalPolicyRefund',normal_refund);
end if;
insert into manager_approval_requests(request_type,related_entity_type,related_entity_id,reservation_id,guest_request_id,department,severity,reason,requested_action,normal_policy_result,requested_by)
values(p_request_type,p_related_entity_type,p_related_entity_id,p_reservation_id,p_guest_request_id,lower(trim(p_department)),p_severity,trim(p_reason),coalesce(p_requested_action,'{}'),normal_result,p_staff_user_id)returning id into aid;
insert into audit_logs(user_id,action,entity_type,entity_id,after_data)values(p_staff_user_id,'request_manager_approval','manager_approval',aid::text,jsonb_build_object('type',p_request_type,'reason',trim(p_reason),'relatedEntityId',p_related_entity_id));
return aid;exception when unique_violation then raise exception'APPROVAL_ALREADY_PENDING';end$$;

create or replace function public.review_manager_approval(p_approval_id uuid,p_decision text,p_reason text,p_expected_version integer,p_manager_user_id uuid)returns jsonb language plpgsql security definer set search_path=public as $$
declare actor text;a manager_approval_requests%rowtype;r reservations%rowtype;available_same int;available_target int;inventory int;reserved int;held int;target_type text;requested_amount numeric;deposit_paid numeric;already_refunded numeric;i invoices%rowtype;rid uuid;begin
select role into actor from user_accounts where id=p_manager_user_id and active;if actor not in('owner','admin','manager')then raise exception'MANAGER_REVIEW_FORBIDDEN';end if;
if p_decision not in('approve','reject')or nullif(trim(p_reason),'')is null then raise exception'INVALID_MANAGER_DECISION';end if;
select * into a from manager_approval_requests where id=p_approval_id for update;if not found then raise exception'APPROVAL_NOT_FOUND';end if;
if a.status<>'pending'or a.version<>p_expected_version then raise exception'APPROVAL_ALREADY_REVIEWED';end if;if a.requested_by=p_manager_user_id then raise exception'SELF_APPROVAL_FORBIDDEN';end if;
if a.reservation_id is not null then select * into r from reservations where id=a.reservation_id for update;if not found then raise exception'APPROVAL_STALE';end if;end if;
if a.request_type in('room_upgrade','reservation_modification','early_check_in','late_checkout','checkout_exception')and r.status in('cancelled','no_show','checked_out')then raise exception'APPROVAL_STALE';end if;
if p_decision='approve'and a.request_type='room_upgrade'then
 target_type:=nullif(a.requested_action->>'requestedRoomType','');if target_type is null or target_type=r.room_type then raise exception'INVALID_UPGRADE_REQUEST';end if;
 select count(*)into available_same from rooms x where x.type=r.room_type and x.status='available'and x.housekeeping='clean'and not exists(select 1 from maintenance_orders m where m.room_id=x.id and m.status in('open','in_progress'))and not exists(select 1 from reservation_room_assignments ra where ra.room_id=x.id and ra.status='active'and ra.reservation_id<>r.id and ra.check_in<r.check_out and ra.check_out>r.check_in);
 if available_same>0 then raise exception'SAME_TYPE_ROOM_AVAILABLE';end if;
 select count(*)into available_target from rooms x where x.type=target_type and x.status='available'and x.housekeeping='clean'and not exists(select 1 from maintenance_orders m where m.room_id=x.id and m.status in('open','in_progress'))and not exists(select 1 from reservation_room_assignments ra where ra.room_id=x.id and ra.status='active'and ra.reservation_id<>r.id and ra.check_in<r.check_out and ra.check_out>r.check_in);
 if available_target=0 then raise exception'UPGRADE_ROOM_UNAVAILABLE';end if;
end if;
if p_decision='approve'and a.request_type='reservation_modification'then
 if nullif(a.requested_action->>'checkIn','')is null or nullif(a.requested_action->>'checkOut','')is null or(a.requested_action->>'checkOut')::date<=(a.requested_action->>'checkIn')::date then raise exception'INVALID_MODIFICATION_REQUEST';end if;
 target_type:=coalesce(nullif(a.requested_action->>'roomType',''),r.room_type);
 if r.status not in('pending','confirmed')then raise exception'APPROVAL_STALE';end if;perform pg_advisory_xact_lock(hashtextextended(target_type,0));perform expire_booking_holds();
 select count(*)into inventory from rooms x where x.type=target_type and x.status<>'maintenance'and((a.requested_action->>'checkIn')::date>current_date or x.housekeeping='clean');
 select count(*)into reserved from reservations y where y.id<>r.id and y.room_type=target_type and y.status in('pending','confirmed','checked_in')and y.check_in<(a.requested_action->>'checkOut')::date and y.check_out>(a.requested_action->>'checkIn')::date;
 select count(*)into held from booking_holds h where h.room_type=target_type and h.status in('active','payment_submitted')and h.expires_at>now()and h.reservation_id is null and h.check_in<(a.requested_action->>'checkOut')::date and h.check_out>(a.requested_action->>'checkIn')::date;available_target:=inventory-reserved-held;
 if available_target<=0 then raise exception'MODIFICATION_INVENTORY_UNAVAILABLE';end if;
end if;
if p_decision='approve'and a.request_type='early_check_in'then
 if r.status<>'confirmed'or r.room_id is null or not exists(select 1 from rooms x where x.id=r.room_id and x.status='available'and x.housekeeping='clean'and not exists(select 1 from maintenance_orders m where m.room_id=x.id and m.status in('open','in_progress')))then raise exception'EARLY_CHECKIN_NOT_SAFE';end if;
end if;
if p_decision='approve'and a.request_type='late_checkout'then
 if r.status<>'checked_in'or nullif(a.requested_action->>'requestedUntil','')is null then raise exception'INVALID_LATE_CHECKOUT';end if;
 if exists(select 1 from reservation_room_assignments ra where ra.room_id=r.room_id and ra.reservation_id<>r.id and ra.status='active'and ra.check_in<=((a.requested_action->>'requestedUntil')::timestamptz at time zone'Asia/Manila')::date and ra.check_out>r.check_out)then raise exception'LATE_CHECKOUT_CONFLICT';end if;
end if;
if p_decision='approve'and a.request_type='guest_compensation'then requested_amount:=coalesce((a.requested_action->>'amount')::numeric,0);select * into i from invoices where reservation_id=r.id for update;if not found or requested_amount<=0 or requested_amount>i.amount then raise exception'COMPENSATION_EXCEEDS_FOLIO';end if;end if;
if p_decision='approve'and a.request_type='checkout_exception'then if r.status<>'checked_in'or nullif(a.requested_action->>'arrangement','')is null then raise exception'INVALID_CHECKOUT_EXCEPTION';end if;end if;
if p_decision='approve'and a.request_type='refund_exception'then
 requested_amount:=coalesce((a.requested_action->>'amount')::numeric,0);select coalesce(sum(amount),0)into deposit_paid from payments where reservation_id=r.id and purpose='reservation_deposit'and status='paid';
 select coalesce(sum(amount),0)into already_refunded from payments where reservation_id=r.id and purpose='refund'and status='paid';if requested_amount<=0 or requested_amount>deposit_paid-already_refunded then raise exception'REFUND_EXCEPTION_EXCEEDS_SETTLED_PAYMENT';end if;
 select * into i from invoices where reservation_id=r.id for update;insert into refund_requests(reservation_id,invoice_id,requested_by,reason,paid_deposit,refund_basis_points,eligible_amount,status,exception_approval_id,normal_policy_amount)
 values(r.id,i.id,a.requested_by,a.reason,deposit_paid,0,round(requested_amount,2),'pending',a.id,coalesce((a.normal_policy_result->>'normalPolicyRefund')::numeric,0))returning id into rid;
end if;
update manager_approval_requests set status=case when p_decision='approve'then'approved'else'rejected'end,reviewed_by=p_manager_user_id,reviewed_at=now(),decision_reason=trim(p_reason),
 execution_status=case when p_decision='reject'then'not_required'when request_type='guest_escalation'then'executed'else'awaiting_execution'end,executed_by=case when p_decision='approve'and request_type='guest_escalation'then p_manager_user_id else null end,executed_at=case when p_decision='approve'and request_type='guest_escalation'then now()else null end,version=version+1,updated_at=now()where id=a.id;
if a.request_type='guest_escalation'and p_decision='approve'then update guest_requests set escalation_status='coordinated',manager_resolution=trim(p_reason)where id=a.guest_request_id;end if;
insert into manager_notes(approval_id,note,created_by)values(a.id,trim(p_reason),p_manager_user_id);
insert into audit_logs(user_id,action,entity_type,entity_id,before_data,after_data)values(p_manager_user_id,'manager_'||p_decision,'manager_approval',a.id::text,jsonb_build_object('status',a.status,'version',a.version),jsonb_build_object('status',case when p_decision='approve'then'approved'else'rejected'end,'reason',trim(p_reason),'refundRequestId',rid));
return jsonb_build_object('status',case when p_decision='approve'then'approved'else'rejected'end,'executionStatus',case when p_decision='reject'then'not_required'when a.request_type='guest_escalation'then'executed'else'awaiting_execution'end,'refundRequestId',rid);end$$;

create or replace function public.front_desk_execute_manager_approval(p_approval_id uuid,p_room_id text,p_staff_user_id uuid)returns jsonb language plpgsql security definer set search_path=public as $$
declare actor text;a manager_approval_requests%rowtype;r reservations%rowtype;oldroom rooms%rowtype;newroom rooms%rowtype;assignment reservation_room_assignments%rowtype;t room_types%rowtype;i invoices%rowtype;new_total numeric;new_paid numeric;available_same int;inventory int;reserved int;held int;begin
select role into actor from user_accounts where id=p_staff_user_id and active;if actor not in('owner','admin','front_desk')then raise exception'FRONT_DESK_EXECUTION_FORBIDDEN';end if;
select * into a from manager_approval_requests where id=p_approval_id for update;if not found or a.status<>'approved'or a.execution_status<>'awaiting_execution'then raise exception'APPROVAL_NOT_EXECUTABLE';end if;
select * into r from reservations where id=a.reservation_id for update;if not found or r.status in('cancelled','no_show','checked_out')then raise exception'APPROVAL_STALE';end if;
if a.request_type='room_upgrade'then
 select count(*)into available_same from rooms x where x.type=r.room_type and x.status='available'and x.housekeeping='clean'and not exists(select 1 from maintenance_orders m where m.room_id=x.id and m.status in('open','in_progress'))and not exists(select 1 from reservation_room_assignments ra where ra.room_id=x.id and ra.status='active'and ra.reservation_id<>r.id and ra.check_in<r.check_out and ra.check_out>r.check_in);if available_same>0 then raise exception'APPROVAL_STALE';end if;
 select * into oldroom from rooms where id=r.room_id for update;select * into newroom from rooms where(id=p_room_id or number=p_room_id)for update;
 if not found or newroom.type<>(a.requested_action->>'requestedRoomType')or newroom.status<>'available'or newroom.housekeeping<>'clean'then raise exception'UPGRADE_ROOM_NOT_READY';end if;
 if exists(select 1 from maintenance_orders where room_id=newroom.id and status in('open','in_progress'))or exists(select 1 from reservation_room_assignments where room_id=newroom.id and reservation_id<>r.id and status='active'and check_in<r.check_out and check_out>r.check_in)then raise exception'UPGRADE_ROOM_UNAVAILABLE';end if;
 select * into assignment from reservation_room_assignments where reservation_id=r.id and status='active'for update;if found then update reservation_room_assignments set status='reassigned',released_at=now(),reason=a.reason where id=assignment.id;end if;
 insert into reservation_room_assignments(reservation_id,room_id,check_in,check_out,assigned_by,reason,is_upgrade,authorized_by)values(r.id,newroom.id,r.check_in,r.check_out,p_staff_user_id,a.reason,true,a.reviewed_by);
 update reservations set room_id=newroom.id,room_number=newroom.number,room_type=newroom.type where id=r.id;update rooms set status=case when r.status='checked_in'then'occupied'else'reserved'end where id=newroom.id;if not coalesce((a.requested_action->>'waived')::boolean,false)and coalesce((a.requested_action->>'priceDifference')::numeric,0)>0 then select * into i from invoices where reservation_id=r.id for update;if not found then raise exception'FOLIO_NOT_FOUND';end if;insert into folio_charges(invoice_id,reservation_id,description,category,amount,posted_by,idempotency_key,source,source_record_id)values(i.id,r.id,'Manager-approved room upgrade to '||newroom.type,'upgrade',round((a.requested_action->>'priceDifference')::numeric,2),p_staff_user_id,a.id,'manager_approval',a.id::text);update invoices set amount=round(amount+round((a.requested_action->>'priceDifference')::numeric,2),2)where id=i.id;perform sync_invoice_financials(i.id);end if;
 if oldroom.id is not null then update rooms set status='dirty',housekeeping='dirty'where id=oldroom.id;insert into housekeeping_tasks(room_id,room_number,task,priority,status,due,notes)values(oldroom.id,oldroom.number,'Manager-approved room-change turnover','high','pending','Before next arrival',a.reason);end if;
elsif a.request_type='reservation_modification'then
 if r.status not in('pending','confirmed')then raise exception'APPROVAL_STALE';end if;select * into t from room_types where name=coalesce(nullif(a.requested_action->>'roomType',''),r.room_type)and active;if not found then raise exception'ROOM_TYPE_UNAVAILABLE';end if;perform pg_advisory_xact_lock(hashtextextended(t.name,0));perform expire_booking_holds();
 select count(*)into inventory from rooms x where x.type=t.name and x.status<>'maintenance'and((a.requested_action->>'checkIn')::date>current_date or x.housekeeping='clean');select count(*)into reserved from reservations y where y.id<>r.id and y.room_type=t.name and y.status in('pending','confirmed','checked_in')and y.check_in<(a.requested_action->>'checkOut')::date and y.check_out>(a.requested_action->>'checkIn')::date;select count(*)into held from booking_holds h where h.room_type=t.name and h.status in('active','payment_submitted')and h.expires_at>now()and h.reservation_id is null and h.check_in<(a.requested_action->>'checkOut')::date and h.check_out>(a.requested_action->>'checkIn')::date;if inventory-reserved-held<=0 then raise exception'MODIFICATION_INVENTORY_UNAVAILABLE';end if;
 if r.room_id is not null then select * into oldroom from rooms where id=r.room_id for update;end if;new_total:=round(t.base_rate*((a.requested_action->>'checkOut')::date-(a.requested_action->>'checkIn')::date),2);select * into i from invoices where reservation_id=r.id for update;new_paid:=i.paid;
 update reservations set check_in=(a.requested_action->>'checkIn')::date,check_out=(a.requested_action->>'checkOut')::date,room_type=t.name,total=new_total,room_id=null,room_number=null where id=r.id;
 update invoices set amount=new_total,balance=greatest(new_total-new_paid,0),credit_balance=greatest(new_paid-new_total,0),status=case when new_paid>new_total then'credit'when new_paid=new_total then'paid'when new_paid>0 then'partial'else'unpaid'end where id=i.id;
 update reservation_room_assignments set status='cancelled',released_at=now(),reason='Reservation modification requires reassignment'where reservation_id=r.id and status='active';if oldroom.id is not null then update rooms set status=case when housekeeping='clean'then'available'else'dirty'end where id=oldroom.id and status='reserved';end if;
elsif a.request_type='early_check_in'then update reservations set early_check_in_approved_until=now()+interval'8 hours'where id=r.id;
elsif a.request_type='late_checkout'then if r.status<>'checked_in'or exists(select 1 from reservation_room_assignments ra where ra.room_id=r.room_id and ra.reservation_id<>r.id and ra.status='active'and ra.check_in<=((a.requested_action->>'requestedUntil')::timestamptz at time zone'Asia/Manila')::date and ra.check_out>r.check_out)then raise exception'APPROVAL_STALE';end if;update reservations set late_checkout_until=(a.requested_action->>'requestedUntil')::timestamptz where id=r.id;
elsif a.request_type='checkout_exception'then if r.status<>'checked_in'or nullif(a.requested_action->>'arrangement','')is null then raise exception'APPROVAL_STALE';end if;select * into oldroom from rooms where id=r.room_id for update;update reservations set status='checked_out',checked_out_at=now()where id=r.id;update rooms set status='dirty',housekeeping='dirty'where id=r.room_id;update reservation_room_assignments set status='released',released_at=now(),reason='Manager-approved checkout exception; balance remains collectible'where reservation_id=r.id and status='active';if not exists(select 1 from housekeeping_tasks where room_id=r.room_id and status in('pending','in_progress'))then insert into housekeeping_tasks(room_id,room_number,task,priority,status,due,notes)values(r.room_id,oldroom.number,'Checkout turnover','high','pending','Before next arrival','Checkout exception executed; folio balance retained: '||(a.requested_action->>'arrangement'));end if;
else raise exception'APPROVAL_REQUIRES_OTHER_DEPARTMENT';end if;
update manager_approval_requests set execution_status='executed',executed_by=p_staff_user_id,executed_at=now(),version=version+1,updated_at=now()where id=a.id;
insert into audit_logs(user_id,action,entity_type,entity_id,after_data)values(p_staff_user_id,'execute_manager_approval','manager_approval',a.id::text,jsonb_build_object('requestType',a.request_type,'reservationId',r.id,'roomId',p_room_id));
return jsonb_build_object('status','executed','requestType',a.request_type,'reservationId',r.id);end$$;

create or replace function public.front_desk_check_in(p_reservation_id text,p_room_id text,p_staff_user_id uuid)returns void language plpgsql security definer set search_path=public as $$
declare actor text;r reservations%rowtype;room rooms%rowtype;i invoices%rowtype;policy jsonb;tz text;local_now timestamp;assignment reservation_room_assignments%rowtype;early_approved boolean;begin
select role into actor from user_accounts where id=p_staff_user_id and active;if actor not in('owner','admin','front_desk')then raise exception'CHECKIN_FORBIDDEN';end if;perform expire_booking_holds();
select * into r from reservations where id=p_reservation_id for update;if not found or r.status<>'confirmed'then raise exception'RESERVATION_NOT_CHECKIN_READY';end if;if r.guest_id is null or nullif(trim(r.guest_name),'')is null then raise exception'GUEST_DETAILS_REQUIRED';end if;
if lower(coalesce(r.source,''))='website'and coalesce(r.deposit_required,0)>0 and(coalesce(r.deposit,0)<r.deposit_required or r.payment_status not in('partial','paid','credit'))then raise exception'RESERVATION_DEPOSIT_REQUIRED';end if;
policy:=coalesce(r.operational_policy_snapshot,current_operational_policy_snapshot());tz:=coalesce(policy->>'hotelTimezone','Asia/Manila');local_now:=now()at time zone tz;early_approved:=coalesce(r.early_check_in_approved_until>now(),false);
if local_now::date<r.check_in or local_now::date>=r.check_out then raise exception'OUTSIDE_CHECKIN_WINDOW';end if;if local_now<(r.check_in+coalesce((policy->>'checkInTime')::time,'15:00'::time))and not coalesce((policy->>'earlyCheckInAllowed')::boolean,false)and not early_approved then raise exception'EARLY_CHECKIN_NOT_ALLOWED';end if;
if coalesce((policy->>'validIdRequired')::boolean,true)and r.identity_status<>'verified'then raise exception'IDENTITY_VERIFICATION_REQUIRED';end if;select * into i from invoices where reservation_id=r.id for update;if not found then raise exception'FOLIO_NOT_FOUND';end if;if coalesce(i.balance,0)>0 then raise exception'REMAINING_BALANCE_REQUIRED';end if;
select * into room from rooms where id=p_room_id or number=p_room_id limit 1 for update;if not found or room.type<>r.room_type then raise exception'ROOM_TYPE_MISMATCH';end if;if room.status<>'available'or room.housekeeping<>'clean'then raise exception'ROOM_NOT_READY';end if;if exists(select 1 from maintenance_orders where room_id=room.id and status in('open','in_progress'))then raise exception'ROOM_UNDER_MAINTENANCE';end if;
if exists(select 1 from reservation_room_assignments where room_id=room.id and reservation_id<>r.id and status='active'and check_in<r.check_out and check_out>r.check_in)then raise exception'ROOM_ALREADY_ASSIGNED';end if;
select * into assignment from reservation_room_assignments where reservation_id=r.id and status='active'for update;if found and assignment.room_id<>room.id then update reservation_room_assignments set status='reassigned',released_at=now(),reason='Changed during check-in'where id=assignment.id;assignment.id:=null;end if;
if assignment.id is null then insert into reservation_room_assignments(reservation_id,room_id,check_in,check_out,assigned_by,reason)values(r.id,room.id,r.check_in,r.check_out,p_staff_user_id,'Check-in assignment');end if;
update reservations set room_id=room.id,room_number=room.number,status='checked_in',checked_in_at=coalesce(checked_in_at,now())where id=r.id;update rooms set status='occupied'where id=room.id;
insert into audit_logs(user_id,action,entity_type,entity_id,before_data,after_data)values(p_staff_user_id,'reservation_check_in','reservation',r.id,jsonb_build_object('status',r.status,'roomId',r.room_id),jsonb_build_object('status','checked_in','roomId',room.id,'room',room.number,'managerEarlyApproval',early_approved));end$$;

create or replace function public.complete_housekeeping_task(p_task_id text,p_staff_user_id uuid)returns void language plpgsql security definer set search_path=public as $$
declare actor text;t housekeeping_tasks%rowtype;blocked boolean;begin select role into actor from user_accounts where id=p_staff_user_id and active;if actor not in('owner','admin','housekeeping')then raise exception'HOUSEKEEPING_COMPLETION_FORBIDDEN';end if;
select * into t from housekeeping_tasks where id=p_task_id for update;if not found then raise exception'TASK_NOT_FOUND';end if;update housekeeping_tasks set status='completed',completed_at=now()where id=t.id;
if t.room_id is not null then select exists(select 1 from maintenance_orders where room_id=t.room_id and status in('open','in_progress'))into blocked;update rooms set housekeeping='clean',status=case when blocked then'maintenance'else'available'end where id=t.room_id and status<>'occupied';end if;
insert into audit_logs(user_id,action,entity_type,entity_id,after_data)values(p_staff_user_id,'complete_housekeeping_task','housekeeping_task',t.id,jsonb_build_object('roomId',t.room_id));end$$;
create or replace function public.resolve_maintenance_order(p_order_id text,p_staff_user_id uuid)returns void language plpgsql security definer set search_path=public as $$
declare actor text;m maintenance_orders%rowtype;begin select role into actor from user_accounts where id=p_staff_user_id and active;if actor not in('owner','admin','maintenance')then raise exception'MAINTENANCE_RESOLUTION_FORBIDDEN';end if;
select * into m from maintenance_orders where id=p_order_id for update;if not found then raise exception'WORK_ORDER_NOT_FOUND';end if;update maintenance_orders set status='resolved',resolved_at=now()where id=m.id;
if m.room_id is not null then update rooms set status='dirty',housekeeping='dirty'where id=m.room_id and status<>'occupied';
if not exists(select 1 from housekeeping_tasks where room_id=m.room_id and status in('pending','in_progress'))then insert into housekeeping_tasks(room_id,room_number,task,priority,status,due,notes)select id,number,'Post-maintenance clean and readiness check','normal','pending','Before next arrival','Maintenance resolved; cleaning is required before return to service'from rooms where id=m.room_id;end if;end if;
insert into audit_logs(user_id,action,entity_type,entity_id,after_data)values(p_staff_user_id,'resolve_maintenance_order','maintenance_order',m.id,jsonb_build_object('roomId',m.room_id));end$$;

create or replace function public.manager_prioritize_housekeeping(p_task_id text,p_priority text,p_reason text,p_manager_user_id uuid)returns void language plpgsql security definer set search_path=public as $$
declare actor text;t housekeeping_tasks%rowtype;begin select role into actor from user_accounts where id=p_manager_user_id and active;if actor not in('owner','admin','manager')then raise exception'MANAGER_COORDINATION_FORBIDDEN';end if;
if p_priority not in('normal','high','urgent')or nullif(trim(p_reason),'')is null then raise exception'INVALID_PRIORITY_COORDINATION';end if;select * into t from housekeeping_tasks where id=p_task_id for update;if not found or t.status='completed'then raise exception'TASK_NOT_COORDINATABLE';end if;
update housekeeping_tasks set priority=p_priority,notes=concat_ws(E'\n',notes,'Manager priority: '||trim(p_reason))where id=t.id;insert into audit_logs(user_id,action,entity_type,entity_id,before_data,after_data)values(p_manager_user_id,'manager_prioritize_housekeeping','housekeeping_task',t.id,jsonb_build_object('priority',t.priority),jsonb_build_object('priority',p_priority,'reason',trim(p_reason)));end$$;
create or replace function public.manager_escalate_maintenance(p_order_id text,p_priority text,p_reason text,p_manager_user_id uuid)returns void language plpgsql security definer set search_path=public as $$
declare actor text;m maintenance_orders%rowtype;begin select role into actor from user_accounts where id=p_manager_user_id and active;if actor not in('owner','admin','manager')then raise exception'MANAGER_COORDINATION_FORBIDDEN';end if;
if p_priority not in('high','urgent')or nullif(trim(p_reason),'')is null then raise exception'INVALID_MAINTENANCE_ESCALATION';end if;select * into m from maintenance_orders where id=p_order_id for update;if not found or m.status='resolved'then raise exception'WORK_ORDER_NOT_ESCALATABLE';end if;
update maintenance_orders set priority=p_priority,notes=concat_ws(E'\n',notes,'Manager escalation: '||trim(p_reason))where id=m.id;insert into audit_logs(user_id,action,entity_type,entity_id,before_data,after_data)values(p_manager_user_id,'manager_escalate_maintenance','maintenance_order',m.id,jsonb_build_object('priority',m.priority),jsonb_build_object('priority',p_priority,'reason',trim(p_reason)));end$$;

create or replace function public.accounting_execute_manager_financial_approval(p_approval_id uuid,p_staff_user_id uuid)returns jsonb language plpgsql security definer set search_path=public as $$
declare actor text;a manager_approval_requests%rowtype;i invoices%rowtype;amount numeric;result jsonb;adjustment_id uuid;begin
select role into actor from user_accounts where id=p_staff_user_id and active;if actor not in('owner','admin','accounting')then raise exception'ACCOUNTING_EXECUTION_FORBIDDEN';end if;
select * into a from manager_approval_requests where id=p_approval_id for update;if not found or a.status<>'approved'or a.execution_status<>'awaiting_execution'or a.request_type<>'guest_compensation'then raise exception'APPROVAL_NOT_EXECUTABLE';end if;
select * into i from invoices where reservation_id=a.reservation_id for update;if not found then raise exception'FOLIO_NOT_FOUND';end if;amount:=coalesce((a.requested_action->>'amount')::numeric,0);if amount<=0 or amount>i.amount then raise exception'COMPENSATION_EXCEEDS_FOLIO';end if;
result:=accounting_record_adjustment(a.reservation_id,'credit','credit',amount,'Manager-approved service recovery: '||a.reason,a.id,p_staff_user_id);adjustment_id:=(result->>'adjustmentId')::uuid;
update financial_adjustments set manager_approval_id=a.id where id=adjustment_id and manager_approval_id is null;update manager_approval_requests set execution_status='executed',executed_by=p_staff_user_id,executed_at=now(),version=version+1,updated_at=now()where id=a.id;
insert into audit_logs(user_id,action,entity_type,entity_id,after_data)values(p_staff_user_id,'execute_manager_financial_approval','manager_approval',a.id::text,jsonb_build_object('adjustmentId',adjustment_id,'amount',amount,'reservationId',a.reservation_id));return result||jsonb_build_object('status','executed','approvalId',a.id);end$$;
revoke all on function public.accounting_execute_manager_financial_approval(uuid,uuid)from public;

create or replace function public.sync_manager_financial_execution()returns trigger language plpgsql security definer set search_path=public as $$
begin if new.status='processed'and old.status is distinct from new.status and new.exception_approval_id is not null then update manager_approval_requests set execution_status='executed',executed_by=new.processed_by,executed_at=new.processed_at,version=version+1,updated_at=now()where id=new.exception_approval_id and execution_status='awaiting_execution';end if;return new;end$$;
drop trigger if exists refund_completes_manager_approval on public.refund_requests;create trigger refund_completes_manager_approval after update on public.refund_requests for each row execute function public.sync_manager_financial_execution();
revoke all on function public.sync_manager_financial_execution()from public;

revoke all on function public.request_manager_approval(text,text,text,text,uuid,text,text,text,jsonb,uuid),public.review_manager_approval(uuid,text,text,integer,uuid),public.front_desk_execute_manager_approval(uuid,text,uuid),public.manager_prioritize_housekeeping(text,text,text,uuid),public.manager_escalate_maintenance(text,text,text,uuid),public.accounting_execute_manager_financial_approval(uuid,uuid)from public;
grant execute on function public.request_manager_approval(text,text,text,text,uuid,text,text,text,jsonb,uuid),public.review_manager_approval(uuid,text,text,integer,uuid),public.front_desk_execute_manager_approval(uuid,text,uuid),public.manager_prioritize_housekeeping(text,text,text,uuid),public.manager_escalate_maintenance(text,text,text,uuid),public.accounting_execute_manager_financial_approval(uuid,uuid)to service_role;
