-- Integrated Front Desk operations: assignment history, staff bookings, room changes, extensions, and operational timestamps.
create extension if not exists btree_gist;
alter table public.hotel_operational_policies add column if not exists early_check_in_allowed boolean not null default false;
alter table public.reservations add column if not exists checked_in_at timestamptz;
alter table public.reservations add column if not exists checked_out_at timestamptz;

create table if not exists public.reservation_room_assignments(
 id uuid primary key default gen_random_uuid(),reservation_id text not null references public.reservations(id)on delete restrict,room_id text not null references public.rooms(id)on delete restrict,
 check_in date not null,check_out date not null,assigned_by uuid references public.user_accounts(id)on delete set null,assigned_at timestamptz not null default now(),
 released_at timestamptz,status text not null default 'active'check(status in('active','reassigned','completed','cancelled','no_show')),
 reason text,is_upgrade boolean not null default false,authorized_by uuid references public.user_accounts(id)on delete set null,check(check_out>check_in));
create unique index if not exists reservation_active_room_unique on public.reservation_room_assignments(reservation_id)where status='active';
do $$begin alter table public.reservation_room_assignments add constraint room_assignment_no_overlap exclude using gist(room_id with =,daterange(check_in,check_out,'[)')with &&)where(status='active');exception when duplicate_object or duplicate_table then null;end$$;
create index if not exists room_assignment_history_idx on public.reservation_room_assignments(reservation_id,assigned_at desc);
alter table public.reservation_room_assignments enable row level security;
insert into public.reservation_room_assignments(reservation_id,room_id,check_in,check_out,assigned_at,released_at,status,reason)
select r.id,r.room_id,r.check_in,r.check_out,r.created_at,case when r.status in('checked_out','cancelled','no_show')then coalesce(r.checked_out_at,now())end,
case r.status when'checked_out'then'completed'when'cancelled'then'cancelled'when'no_show'then'no_show'else'active'end,'Historical assignment backfill'
from public.reservations r where r.room_id is not null and not exists(select 1 from public.reservation_room_assignments a where a.reservation_id=r.id);

create or replace function public.current_operational_policy_snapshot()returns jsonb language sql stable security definer set search_path=public as $$
select jsonb_build_object('hotelTimezone',hotel_timezone,'checkInTime',check_in_time::text,'checkOutTime',check_out_time::text,'noShowCutoffTime',no_show_cutoff_time::text,'validIdRequired',valid_id_required,'minimumBookingAge',minimum_booking_age,'cancellationFullRefundDays',cancellation_full_refund_days,'cancellationPartialRefundDays',cancellation_partial_refund_days,'cancellationPartialRefundBasisPoints',cancellation_partial_refund_basis_points,'selfServiceModificationDays',self_service_modification_days,'incidentalsDue',incidentals_due,'petsAllowed',pets_allowed,'smokingAllowed',smoking_allowed,'specialRequestsGuaranteed',special_requests_guaranteed,'emailVerificationRequired',email_verification_required,'earlyCheckInAllowed',early_check_in_allowed)from hotel_operational_policies where key='default'$$;

create or replace function public.front_desk_create_reservation(p_guest_name text,p_email text,p_phone text,p_room_type text,p_check_in date,p_check_out date,p_guest_count integer,p_source text,p_special_requests text,p_expected_arrival text,p_idempotency_key uuid,p_staff_user_id uuid)
returns table(reservation_id text,confirmation_number text,total numeric)language plpgsql security definer set search_path=public as $$
declare actor text;t room_types%rowtype;inventory int;reserved int;guest text;rid text;iid text;confirmation text;amount numeric;begin
select role into actor from user_accounts where id=p_staff_user_id and active;if actor not in('owner','admin','manager','front_desk')then raise exception'STAFF_RESERVATION_FORBIDDEN';end if;
if p_check_in<(now()at time zone'Asia/Manila')::date or p_check_out<=p_check_in then raise exception'INVALID_DATES';end if;if p_guest_count<1 then raise exception'INVALID_GUEST_COUNT';end if;
if nullif(trim(p_guest_name),'')is null or nullif(trim(p_email),'')is null or nullif(trim(p_phone),'')is null then raise exception'INVALID_GUEST_DETAILS';end if;if p_source not in('Front Desk','Walk-In','Phone')then raise exception'INVALID_BOOKING_SOURCE';end if;
select id into rid from reservations where idempotency_key=p_idempotency_key;if found then return query select r.id,r.confirmation_number,r.total from reservations r where r.id=rid;return;end if;
perform pg_advisory_xact_lock(hashtextextended(lower(p_room_type),0));select * into t from room_types where name=p_room_type and active;if not found or p_guest_count>t.max_guests then raise exception'ROOM_TYPE_UNAVAILABLE';end if;
select count(*)into inventory from rooms where type=p_room_type and status<>'maintenance';select count(*)into reserved from reservations where room_type=p_room_type and status in('pending','confirmed','checked_in')and check_in<p_check_out and check_out>p_check_in;
if inventory-reserved<=0 then raise exception'ROOM_TYPE_UNAVAILABLE';end if;amount:=round(t.base_rate*(p_check_out-p_check_in),2);
select id into guest from guests where lower(email)=lower(trim(p_email))limit 1 for update;if guest is null then insert into guests(name,email,phone)values(trim(p_guest_name),lower(trim(p_email)),trim(p_phone))returning id into guest;else update guests set name=trim(p_guest_name),phone=trim(p_phone)where id=guest;end if;
confirmation:='HVN-'||to_char(clock_timestamp(),'YYMMDD')||'-'||upper(substr(replace(gen_random_uuid()::text,'-',''),1,6));
insert into reservations(guest_id,guest_name,guest_email,room_type,check_in,check_out,guests,status,source,total,deposit,deposit_required,special_requests,expected_arrival,payment_status,confirmation_number,idempotency_key)
values(guest,trim(p_guest_name),lower(trim(p_email)),p_room_type,p_check_in,p_check_out,p_guest_count,'confirmed',p_source,amount,0,0,nullif(trim(p_special_requests),''),nullif(trim(p_expected_arrival),''),'unpaid',confirmation,p_idempotency_key)returning id into rid;
insert into invoices(reservation_id,guest_name,amount,paid,balance,status,due_date)values(rid,trim(p_guest_name),amount,0,amount,'unpaid',p_check_in)returning id into iid;
insert into audit_logs(user_id,action,entity_type,entity_id,after_data)values(p_staff_user_id,'create_staff_reservation','reservation',rid,jsonb_build_object('source',p_source,'roomType',p_room_type,'checkIn',p_check_in,'checkOut',p_check_out,'total',amount));return query select rid,confirmation,amount;end$$;

create or replace function public.front_desk_assign_room(p_reservation_id text,p_room_id text,p_reason text,p_staff_user_id uuid)returns uuid language plpgsql security definer set search_path=public as $$
declare actor text;r reservations%rowtype;room rooms%rowtype;old reservation_room_assignments%rowtype;aid uuid;begin
select role into actor from user_accounts where id=p_staff_user_id and active;if actor not in('owner','admin','manager','front_desk')then raise exception'ROOM_ASSIGNMENT_FORBIDDEN';end if;
select * into r from reservations where id=p_reservation_id for update;if not found or r.status<>'confirmed'then raise exception'RESERVATION_NOT_ASSIGNABLE';end if;select * into room from rooms where id=p_room_id or number=p_room_id limit 1 for update;
if not found or room.type<>r.room_type then raise exception'ROOM_TYPE_MISMATCH';end if;if room.status<>'available'or room.housekeeping<>'clean'then raise exception'ROOM_NOT_READY';end if;if exists(select 1 from maintenance_orders where room_id=room.id and status in('open','in_progress'))then raise exception'ROOM_UNDER_MAINTENANCE';end if;
if exists(select 1 from reservation_room_assignments where room_id=room.id and reservation_id<>r.id and status='active'and check_in<r.check_out and check_out>r.check_in)then raise exception'ROOM_ALREADY_ASSIGNED';end if;
select * into old from reservation_room_assignments where reservation_id=r.id and status='active'for update;if found and old.room_id=room.id then return old.id;elsif found then update reservation_room_assignments set status='reassigned',released_at=now(),reason=coalesce(nullif(trim(p_reason),''),'Pre-arrival reassignment')where id=old.id;end if;
insert into reservation_room_assignments(reservation_id,room_id,check_in,check_out,assigned_by,reason)values(r.id,room.id,r.check_in,r.check_out,p_staff_user_id,nullif(trim(p_reason),''))returning id into aid;update reservations set room_id=room.id,room_number=room.number where id=r.id;
insert into audit_logs(user_id,action,entity_type,entity_id,before_data,after_data)values(p_staff_user_id,'assign_room','reservation',r.id,jsonb_build_object('roomId',old.room_id),jsonb_build_object('roomId',room.id,'roomNumber',room.number,'reason',p_reason));return aid;end$$;
create or replace function public.front_desk_check_in(p_reservation_id text,p_room_id text,p_staff_user_id uuid)returns void language plpgsql security definer set search_path=public as $$
declare actor text;r reservations%rowtype;room rooms%rowtype;i invoices%rowtype;policy jsonb;tz text;local_now timestamp;assignment reservation_room_assignments%rowtype;begin
select role into actor from user_accounts where id=p_staff_user_id and active;if actor not in('owner','admin','manager','front_desk')then raise exception'CHECKIN_FORBIDDEN';end if;perform expire_booking_holds();
select * into r from reservations where id=p_reservation_id for update;if not found or r.status<>'confirmed'then raise exception'RESERVATION_NOT_CHECKIN_READY';end if;if r.guest_id is null or nullif(trim(r.guest_name),'')is null then raise exception'GUEST_DETAILS_REQUIRED';end if;
if lower(coalesce(r.source,''))='website'and coalesce(r.deposit_required,0)>0 and(coalesce(r.deposit,0)<r.deposit_required or r.payment_status not in('partial','paid'))then raise exception'RESERVATION_DEPOSIT_REQUIRED';end if;
policy:=coalesce(r.operational_policy_snapshot,current_operational_policy_snapshot());tz:=coalesce(policy->>'hotelTimezone','Asia/Manila');local_now:=now()at time zone tz;
if local_now::date<r.check_in or local_now::date>=r.check_out then raise exception'OUTSIDE_CHECKIN_WINDOW';end if;if local_now<(r.check_in+coalesce((policy->>'checkInTime')::time,'15:00'::time))and not coalesce((policy->>'earlyCheckInAllowed')::boolean,false)then raise exception'EARLY_CHECKIN_NOT_ALLOWED';end if;
if coalesce((policy->>'validIdRequired')::boolean,true)and r.identity_status<>'verified'then raise exception'IDENTITY_VERIFICATION_REQUIRED';end if;select * into i from invoices where reservation_id=r.id for update;if not found then raise exception'FOLIO_NOT_FOUND';end if;if coalesce(i.balance,0)>0 then raise exception'REMAINING_BALANCE_REQUIRED';end if;
select * into room from rooms where id=p_room_id or number=p_room_id limit 1 for update;if not found or room.type<>r.room_type then raise exception'ROOM_TYPE_MISMATCH';end if;if room.status<>'available'or room.housekeeping<>'clean'then raise exception'ROOM_NOT_READY';end if;if exists(select 1 from maintenance_orders where room_id=room.id and status in('open','in_progress'))then raise exception'ROOM_UNDER_MAINTENANCE';end if;
if exists(select 1 from reservation_room_assignments where room_id=room.id and reservation_id<>r.id and status='active'and check_in<r.check_out and check_out>r.check_in)then raise exception'ROOM_ALREADY_ASSIGNED';end if;
select * into assignment from reservation_room_assignments where reservation_id=r.id and status='active'for update;if found and assignment.room_id<>room.id then update reservation_room_assignments set status='reassigned',released_at=now(),reason='Changed during check-in'where id=assignment.id;assignment.id:=null;end if;
if assignment.id is null then insert into reservation_room_assignments(reservation_id,room_id,check_in,check_out,assigned_by,reason)values(r.id,room.id,r.check_in,r.check_out,p_staff_user_id,'Check-in assignment');end if;
update reservations set room_id=room.id,room_number=room.number,status='checked_in',checked_in_at=coalesce(checked_in_at,now())where id=r.id;update rooms set status='occupied'where id=room.id;
insert into audit_logs(user_id,action,entity_type,entity_id,before_data,after_data)values(p_staff_user_id,'reservation_check_in','reservation',r.id,jsonb_build_object('status',r.status,'roomId',r.room_id),jsonb_build_object('status','checked_in','roomId',room.id,'room',room.number));end$$;

create or replace function public.front_desk_change_room(p_reservation_id text,p_new_room_id text,p_reason text,p_staff_user_id uuid)returns uuid language plpgsql security definer set search_path=public as $$
declare actor text;r reservations%rowtype;oldroom rooms%rowtype;newroom rooms%rowtype;assignment reservation_room_assignments%rowtype;aid uuid;upgrade boolean;begin
select role into actor from user_accounts where id=p_staff_user_id and active;if actor not in('owner','admin','manager','front_desk')then raise exception'ROOM_CHANGE_FORBIDDEN';end if;if nullif(trim(p_reason),'')is null then raise exception'ROOM_CHANGE_REASON_REQUIRED';end if;
select * into r from reservations where id=p_reservation_id for update;if not found or r.status<>'checked_in'or r.room_id is null then raise exception'RESERVATION_NOT_IN_HOUSE';end if;select * into oldroom from rooms where id=r.room_id for update;select * into newroom from rooms where id=p_new_room_id or number=p_new_room_id limit 1 for update;
if not found or newroom.id=oldroom.id then raise exception'INVALID_REPLACEMENT_ROOM';end if;upgrade:=newroom.type<>r.room_type;if upgrade and actor not in('owner','admin','manager')then raise exception'UPGRADE_AUTHORIZATION_REQUIRED';end if;if newroom.status<>'available'or newroom.housekeeping<>'clean'then raise exception'ROOM_NOT_READY';end if;if exists(select 1 from maintenance_orders where room_id=newroom.id and status in('open','in_progress'))then raise exception'ROOM_UNDER_MAINTENANCE';end if;
if exists(select 1 from reservation_room_assignments where room_id=newroom.id and reservation_id<>r.id and status='active'and check_in<r.check_out and check_out>r.check_in)then raise exception'ROOM_ALREADY_ASSIGNED';end if;
select * into assignment from reservation_room_assignments where reservation_id=r.id and status='active'for update;if not found then raise exception'ACTIVE_ASSIGNMENT_NOT_FOUND';end if;update reservation_room_assignments set status='reassigned',released_at=now(),reason=trim(p_reason)where id=assignment.id;
insert into reservation_room_assignments(reservation_id,room_id,check_in,check_out,assigned_by,reason,is_upgrade,authorized_by)values(r.id,newroom.id,r.check_in,r.check_out,p_staff_user_id,trim(p_reason),upgrade,case when upgrade then p_staff_user_id end)returning id into aid;
update rooms set status=case when exists(select 1 from maintenance_orders where room_id=oldroom.id and status in('open','in_progress'))then'maintenance'else'dirty'end,housekeeping='dirty'where id=oldroom.id;update rooms set status='occupied'where id=newroom.id;update reservations set room_id=newroom.id,room_number=newroom.number where id=r.id;
if not exists(select 1 from housekeeping_tasks where room_id=oldroom.id and status in('pending','in_progress'))then insert into housekeeping_tasks(room_id,room_number,task,priority,status,due,notes)values(oldroom.id,oldroom.number,'Room-change turnover','high','pending','Before next assignment','Guest transferred: '||trim(p_reason));end if;
insert into audit_logs(user_id,action,entity_type,entity_id,before_data,after_data)values(p_staff_user_id,'change_room','reservation',r.id,jsonb_build_object('roomId',oldroom.id,'room',oldroom.number),jsonb_build_object('roomId',newroom.id,'room',newroom.number,'upgrade',upgrade,'reason',p_reason));return aid;end$$;

create or replace function public.front_desk_extend_stay(p_reservation_id text,p_new_check_out date,p_reason text,p_idempotency_key uuid,p_staff_user_id uuid)
returns table(new_check_out date,additional_amount numeric,new_balance numeric)language plpgsql security definer set search_path=public as $$
declare actor text;r reservations%rowtype;room rooms%rowtype;t room_types%rowtype;i invoices%rowtype;a reservation_room_assignments%rowtype;added numeric;cid uuid;begin
select role into actor from user_accounts where id=p_staff_user_id and active;if actor not in('owner','admin','manager','front_desk')then raise exception'EXTENSION_FORBIDDEN';end if;if nullif(trim(p_reason),'')is null then raise exception'EXTENSION_REASON_REQUIRED';end if;
select * into r from reservations where id=p_reservation_id for update;if not found or r.status<>'checked_in'or r.room_id is null then raise exception'RESERVATION_NOT_IN_HOUSE';end if;if p_new_check_out<=r.check_out then raise exception'INVALID_EXTENSION_DATE';end if;
select id into cid from folio_charges where idempotency_key=p_idempotency_key;if found then select * into i from invoices where reservation_id=r.id;return query select r.check_out,(select amount from folio_charges where id=cid),i.balance;return;end if;
select * into room from rooms where id=r.room_id for update;select * into a from reservation_room_assignments where reservation_id=r.id and status='active'for update;if not found then raise exception'ACTIVE_ASSIGNMENT_NOT_FOUND';end if;
if exists(select 1 from reservation_room_assignments where room_id=room.id and reservation_id<>r.id and status='active'and check_in<p_new_check_out and check_out>r.check_out)or exists(select 1 from reservations where id<>r.id and room_id=room.id and status in('confirmed','checked_in')and check_in<p_new_check_out and check_out>r.check_out)then raise exception'EXTENSION_REQUIRES_ROOM_CHANGE';end if;
select * into t from room_types where name=r.room_type and active;if not found then raise exception'ROOM_TYPE_UNAVAILABLE';end if;added:=round(t.base_rate*(p_new_check_out-r.check_out),2);select * into i from invoices where reservation_id=r.id for update;if not found then raise exception'FOLIO_NOT_FOUND';end if;
insert into folio_charges(invoice_id,reservation_id,description,category,amount,posted_by,idempotency_key)values(i.id,r.id,'Stay extension through '||p_new_check_out,'extension',added,p_staff_user_id,p_idempotency_key)returning id into cid;
update invoices set amount=amount+added,balance=balance+added,status=case when paid>0 then'partial'else'unpaid'end where id=i.id returning * into i;update reservations set check_out=p_new_check_out,total=total+added,payment_status=case when deposit>0 then'partial'else'unpaid'end where id=r.id;update reservation_room_assignments set check_out=p_new_check_out where id=a.id;
insert into audit_logs(user_id,action,entity_type,entity_id,before_data,after_data)values(p_staff_user_id,'extend_stay','reservation',r.id,jsonb_build_object('checkOut',r.check_out,'total',r.total),jsonb_build_object('checkOut',p_new_check_out,'additionalAmount',added,'reason',p_reason));return query select p_new_check_out,added,i.balance;end$$;
create or replace function public.front_desk_update_guest(p_reservation_id text,p_phone text,p_expected_arrival text,p_operational_notes text,p_staff_user_id uuid)returns void language plpgsql security definer set search_path=public as $$
declare actor text;r reservations%rowtype;g guests%rowtype;begin select role into actor from user_accounts where id=p_staff_user_id and active;if actor not in('owner','admin','manager','front_desk')then raise exception'GUEST_UPDATE_FORBIDDEN';end if;select * into r from reservations where id=p_reservation_id for update;if not found or r.status not in('pending','confirmed','checked_in')then raise exception'RESERVATION_NOT_EDITABLE';end if;select * into g from guests where id=r.guest_id for update;if not found then raise exception'GUEST_NOT_FOUND';end if;
update guests set phone=coalesce(nullif(trim(p_phone),''),phone),special_requests=coalesce(nullif(trim(p_operational_notes),''),special_requests)where id=g.id;update reservations set expected_arrival=coalesce(nullif(trim(p_expected_arrival),''),expected_arrival),special_requests=coalesce(nullif(trim(p_operational_notes),''),special_requests)where id=r.id;
insert into audit_logs(user_id,action,entity_type,entity_id,before_data,after_data)values(p_staff_user_id,'update_guest_operations','guest',g.id,jsonb_build_object('phone',g.phone,'expectedArrival',r.expected_arrival,'notes',r.special_requests),jsonb_build_object('phone',coalesce(nullif(trim(p_phone),''),g.phone),'expectedArrival',coalesce(nullif(trim(p_expected_arrival),''),r.expected_arrival),'notes',coalesce(nullif(trim(p_operational_notes),''),r.special_requests)));end$$;

create or replace function public.front_desk_checkout(p_reservation_id text,p_staff_user_id uuid)returns void language plpgsql security definer set search_path=public as $$
declare actor text;r reservations%rowtype;i invoices%rowtype;a reservation_room_assignments%rowtype;begin select role into actor from user_accounts where id=p_staff_user_id and active;if actor not in('owner','admin','manager','front_desk')then raise exception'CHECKOUT_FORBIDDEN';end if;
select * into r from reservations where id=p_reservation_id for update;if not found or r.status<>'checked_in'then raise exception'RESERVATION_NOT_CHECKOUT_READY';end if;select * into i from invoices where reservation_id=r.id for update;if not found then raise exception'FOLIO_NOT_FOUND';end if;if coalesce(i.balance,0)>0 then raise exception'FOLIO_BALANCE_REQUIRED';end if;
select * into a from reservation_room_assignments where reservation_id=r.id and status='active'for update;if not found then raise exception'ACTIVE_ASSIGNMENT_NOT_FOUND';end if;update reservation_room_assignments set status='completed',released_at=now()where id=a.id;update reservations set status='checked_out',checked_out_at=coalesce(checked_out_at,now())where id=r.id;
update rooms set status='dirty',housekeeping='dirty'where id=a.room_id;if not exists(select 1 from housekeeping_tasks where room_id=a.room_id and status in('pending','in_progress'))then insert into housekeeping_tasks(room_id,room_number,task,priority,status,due,notes)values(a.room_id,r.room_number,'Post-checkout room turnover','high','pending','Before next arrival','Automatically created at checkout');end if;
insert into audit_logs(user_id,action,entity_type,entity_id,before_data,after_data)values(p_staff_user_id,'reservation_checkout','reservation',r.id,jsonb_build_object('status',r.status,'room',r.room_number),jsonb_build_object('status','checked_out','roomStatus','dirty','assignmentStatus','completed'));end$$;

create or replace function public.release_terminal_assignment()returns trigger language plpgsql security definer set search_path=public as $$begin if new.status in('cancelled','no_show')and old.status is distinct from new.status then update reservation_room_assignments set status=case new.status when'cancelled'then'cancelled'else'no_show'end,released_at=now(),reason=coalesce(new.cancellation_reason,reason)where reservation_id=new.id and status='active';end if;return new;end$$;
drop trigger if exists reservations_release_terminal_assignment on public.reservations;create trigger reservations_release_terminal_assignment after update of status on public.reservations for each row execute function public.release_terminal_assignment();

revoke all on table public.reservation_room_assignments from anon,authenticated;
revoke all on function public.front_desk_create_reservation(text,text,text,text,date,date,integer,text,text,text,uuid,uuid)from public;
revoke all on function public.front_desk_assign_room(text,text,text,uuid)from public;revoke all on function public.front_desk_change_room(text,text,text,uuid)from public;
revoke all on function public.front_desk_extend_stay(text,date,text,uuid,uuid)from public;revoke all on function public.front_desk_update_guest(text,text,text,text,uuid)from public;
revoke all on function public.front_desk_check_in(text,text,uuid)from public;revoke all on function public.front_desk_checkout(text,uuid)from public;
grant execute on function public.front_desk_create_reservation(text,text,text,text,date,date,integer,text,text,text,uuid,uuid)to service_role;
grant execute on function public.front_desk_assign_room(text,text,text,uuid)to service_role;grant execute on function public.front_desk_change_room(text,text,text,uuid)to service_role;
grant execute on function public.front_desk_extend_stay(text,date,text,uuid,uuid)to service_role;grant execute on function public.front_desk_update_guest(text,text,text,text,uuid)to service_role;
grant execute on function public.front_desk_check_in(text,text,uuid)to service_role;grant execute on function public.front_desk_checkout(text,uuid)to service_role;